style:	* apply gplv3 header 	* variable declaration grouped together 	* labels to all caps 	* convert one condition if-s to oneliners 	* shift $((OPTIND - 1)) group together with optarg

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,15 +1,27 @@
 #!/bin/sh
 
-# version number
+# ani-cli
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+#
+# Project repository: https://github.com/pystardust/ani-cli
+
+# Version number
 VERSION="1.7.0"
 
-
-# history file path
-logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
-auto_play=0
-
 #######################
-# Auxiliary functions #
+# AUXILIARY FUNCTIONS #
 #######################
 
 help_text () {
@@ -47,7 +59,7 @@ help_text () {
 }
 
 version_text () {
-	inf "Version: $VERSION"  >&2
+	inf "Version: $VERSION" >&2
 }
 
 die () {
@@ -70,14 +82,12 @@ update_script () {
 }
 
 dep_ch () {
-	# checks if programs are present
+	# checks if dependencies are present
 	for dep; do
 		if ! command -v "$dep" >/dev/null ; then
 			err "Program \"$dep\" not found. Please install it."
 			#aria2c is in the package aria2
-			if [ "$dep" = "aria2c" ]; then
-				err "To install aria2c, Type <your_package_manager> aria2"
-			fi
+			[ "$dep" = "aria2c" ] && err "To install aria2c, Type <your_package_manager> aria2"
 			die
 		fi
 	done
@@ -85,17 +95,14 @@ dep_ch () {
 
 
 #############
-# Searching #
+# SEARCHING #
 #############
 
 search_anime () {
 	# get anime name along with its id for search term
 	search=$(printf '%s' "$1" | tr ' ' '-' )
-
-	curl -s "$base_url//search.html" \
-		-G \
-		-d "keyword=$search" |
-	sed -n -E '
+	curl -s "$base_url//search.html" -G -d "keyword=$search" |
+		sed -n -E '
 		s_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p
 		'
 }
@@ -103,7 +110,6 @@ search_anime () {
 search_eps () {
 	# get available episodes for anime_id
 	anime_id=$1
-
 	curl -s "$base_url/category/$anime_id" |
 	sed -n -E '
 		/^[[:space:]]*<a href="#" class="active" ep_start/{
@@ -116,23 +122,18 @@ search_eps () {
 search_for_unwatched () {
 	# compares history with gogoanime, only shows unfinished anime
 	search_results=$*
-
 	unwatched_anime=""
+
 	while read -r anime_id; do
 		current_ep_number="$(search_eps "$anime_id")"
 		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
-		if [ "$current_ep_number" -ge "$history_ep_number" ]
-		then
-			# breaks down with \n because of the display functions
-			unwatched_anime="$unwatched_anime$anime_id
+		# breaks down with \n because of display functions
+		[ "$current_ep_number" -ge "$history_ep_number" ] && unwatched_anime="$unwatched_anime$anime_id
 "
-		fi
 	done <<-EOF
 	$search_results
 	EOF
-	if [ -z "$unwatched_anime" ]; then
-		die "No unwatched episodes"
-	fi
+	[ -z "$unwatched_anime" ] && die "No unwatched episodes"
 	printf "%s" "$unwatched_anime"
 }
 
@@ -156,7 +157,7 @@ search_history () {
 }
 
 ##################
-# URL processing #
+# URL PROCESSING #
 ##################
 
 get_dpage_link() {
@@ -165,13 +166,8 @@ get_dpage_link() {
 	ep_no=$2
 
 	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
-	# dub prefix takes the value "-dub" when dub is needed else is empty
 	anime_page=$(curl -s "$base_url/$anime_id-$ep_no")
-
-	if printf '%s' "$anime_page" | grep -q "404" ; then
-		anime_page=$(curl -s "$base_url/$anime_id-episode-$ep_no")
-	fi
-
+	printf '%s' "$anime_page" | grep -q '404' && anime_page=$(curl -s "$base_url/$anime_id-episode-$ep_no")
 	printf '%s' "$anime_page" |
 		sed -n -E 's/^[[:space:]]*<a href="#" rel="100" data-video="([^"]*)".*/\1/p' |
 		sed 's/^/https:/g'
@@ -179,19 +175,19 @@ get_dpage_link() {
 
 decrypt_link() {
 	ajax_url='https://gogoplay.io/encrypt-ajax.php'
+	secret_key='3235373436353338353932393338333936373634363632383739383333323838'
+	iv='34323036393133333738303038313335'
 
 	#get the id from the url
 	video_id=$(echo "$1" | cut -d\? -f2 | cut -d\& -f1 | sed 's/id=//g')
 
 	#construct ajax parameters
-	secret_key='3235373436353338353932393338333936373634363632383739383333323838'
-	iv='34323036393133333738303038313335'
 	ajax=$(echo "$video_id" | openssl enc -aes256  -K "$secret_key" -iv "$iv" -a)
 
 	#send the request to the ajax url
 	curl -s -H 'x-requested-with:XMLHttpRequest' "$ajax_url" -d "id=$ajax" -d "time=69420691337800813569" |
-	sed -e 's/\].*/\]/' -e 's/\\//g' |
-	grep -Eo 'https:\/\/[-a-zA-Z0-9@:%._\+~#=][a-zA-Z0-9][-a-zA-Z0-9@:%_\+.~#?&\/\/=]*'
+		sed -e 's/\].*/\]/' -e 's/\\//g' |
+		grep -Eo 'https:\/\/[-a-zA-Z0-9@:%._\+~#=][a-zA-Z0-9][-a-zA-Z0-9@:%_\+.~#?&\/\/=]*'
 }
 
 get_video_quality() {
@@ -221,7 +217,7 @@ get_video_quality() {
 
 
 ###############
-# Text output #
+# TEXT OUTPUT #
 ###############
 
 err () {
@@ -269,7 +265,7 @@ menu_line_strong() {
 
 
 #################
-# Input parsing #
+# INPUT PARSING #
 #################
 
 anime_selection () {
@@ -284,30 +280,26 @@ anime_selection () {
 		tput clear
 		choice=1
 	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
-        menu_line_alternate "search for another anime" "a"
-        menu_line_strong "exit" "q"
+        	menu_line_alternate "search for another anime" "a"
+        	menu_line_strong "exit" "q"
 		prompt "Enter choice"
 		choice="$REPLY $REPLY2"
 	fi
+	# Check if input is a number
+	[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
+	# Select respective anime_id
+	count=1
+	while read -r anime_id; do
+		if [ "$count" -eq "$choice" ]; then
+			selection_id=$anime_id
+			break
+		fi
+		count=$((count+1))
+	done <<-EOF
+	$search_results
+	EOF
 
-		# Check if input is a number
-		[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
-		# Select respective anime_id
-		count=1
-		while read -r anime_id; do
-			if [ "$count" -eq "$choice" ]; then
-				selection_id=$anime_id
-				break
-			fi
-			count=$((count+1))
-		done <<-EOF
-		$search_results
-		EOF
-
-	if [ -z "$selection_id" ]; then
-		die "Invalid number entered"
-	fi
-
+	[ -z "$selection_id" ] && die "Invalid number entered"
 	search_ep_result="$(search_eps "$selection_id")"
 	read -r last_ep_number <<-EOF
 	$search_ep_result
@@ -318,17 +310,9 @@ episode_selection () {
 	# using get_dpage_link to get confirmation from episode 0 if it exists,else first_ep_number becomes "1"
 	first_ep_number="0"
 	result=$(get_dpage_link "$anime_id" "$first_ep_number")
-
-	if [ -n "$result" ]; then
-		true
-	else
-		first_ep_number="1"
-	fi
-
+	[ -z "$result" ] && first_ep_number=1
 	if [ "$last_ep_number" -gt "$first_ep_number" ]; then
-
 		inf "Range of episodes can be specified: start_number end_number"
-
 		if [ -z "$ep_choice_to_start" ]; then
 			prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
 			ep_choice_start=$REPLY
@@ -346,9 +330,8 @@ episode_selection () {
 		else
 			ep_choice_start=$ep_choice_to_start && unset ep_choice_to_start
 		fi
-		whether_half="$(echo "$ep_choice_start" | cut -c1-1)"
-		if [ "$whether_half" = "h" ]
-		then
+		whether_half="$(printf '%s\n' "$ep_choice_start" | cut -c1-1)"
+		if [ "$whether_half" = "h" ];then
 			half_ep=1
 			ep_choice_start="$(echo "$ep_choice_start" | cut -c2-)"
 		fi
@@ -363,8 +346,6 @@ episode_selection () {
 		auto_play=1
 		[ "$ep_choice_end" = "-1" ] && ep_choice_end="$last_ep_number"
 	fi
-
-
 }
 
 check_input() {
@@ -380,12 +361,11 @@ check_input() {
 
 
 ##################
-# Video Playback #
+# VIDEO PLAYBACK #
 ##################
 
 append_history () {
-	grep -q -w "${selection_id}" "$logfile" ||
-		printf "%s\t%d\n" "$selection_id" $((episode+1)) >> "$logfile"
+	grep -q -w "${selection_id}" "$logfile" || printf "%s\t%s\n" "$selection_id" $((episode+1)) >> "$logfile"
 }
 
 open_selection() {
@@ -400,7 +380,7 @@ open_selection() {
 open_episode () {
 	anime_id=$1
 	episode=$2
-	# Cool way of clearing screen
+	# cool way of clearing screen
 	tput clear
 	# checking if episode is in range
 	while  [ "$episode" -gt "$last_ep_number" ] || [ -z "$episode"  ]
@@ -438,11 +418,7 @@ open_episode () {
 
 		kill "$PID" >/dev/null 2>&1
 
-		if [ -z "$video_url" ]; then
-			die "Video URL not found"
-		fi
-
-
+		[ -z "$video_url" ] && die "Video URL not found"
 
 		case $player_fn in
 			vlc)
@@ -469,7 +445,7 @@ open_episode () {
 		mv "${logfile}.new" "$logfile"
 	else
 		mkdir -p "$download_dir"
-		inf "Downloading episode $episode ...\n"
+		inf "Downloading episode $episode ..."
 		# add 0 padding to the episode name
 		episode=$(printf "%03d" "$episode")
 		{
@@ -485,14 +461,11 @@ open_episode () {
 }
 
 ############
-# Start Up #
+# START UP #
 ############
 
 # to clear the colors when exited using SIGINT
 trap 'printf "\033[0m"; exit 1' INT HUP
-
-# create history file if none found
-[ -f "$logfile" ] || : > "$logfile"
 
 # default options
 player_fn="mpv" #video player needs to be able to play urls
@@ -502,6 +475,12 @@ quality=best
 scrape=query
 download_dir="."
 choice=""
+auto_play=0
+# history file path
+logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
+
+# create history file if none found
+[ -f "$logfile" ] || : > "$logfile"
 
 while getopts 'vq:dp:chDUVa:' OPT; do
 	case $OPT in
@@ -548,6 +527,7 @@ while getopts 'vq:dp:chDUVa:' OPT; do
 			;;
 	esac
 done
+shift $((OPTIND - 1))
 
 # check for main dependencies
 dep_ch "curl" "sed" "grep" "git" "openssl"
@@ -558,8 +538,6 @@ if [ "$is_download" -eq 0 ]; then
 else
 	dep_ch "aria2c"
 fi
-
-shift $((OPTIND - 1))
 # gogoanime likes to change domains but keep the olds as redirects
 base_url=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm)
 case $scrape in
@@ -577,13 +555,15 @@ case $scrape in
 		search_results=$(search_anime "$query")
 		[ -z "$search_results" ] && die "No search results found"
 		anime_selection "$search_results"
-        while [ "$REPLY" = "a" ]; do
-        	search_another_anime
-        done
-        [ "$REPLY" = "q" ] && exit 0
-        if [ "$REPLY" -gt 0 ]; then episode_selection
-        else die "invalid choice"
-        fi
+        	while [ "$REPLY" = "a" ]; do
+        		search_another_anime
+        	done
+        	[ "$REPLY" = "q" ] && exit 0
+        	if [ "$REPLY" -gt 0 ]; then
+			episode_selection
+        	else
+			die "invalid choice"
+        	fi
 		;;
 	history)
 		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
@@ -591,20 +571,13 @@ case $scrape in
 		search_results=$(search_for_unwatched "$search_results")
 		anime_selection "$search_results"
 		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
-
-
-        while [ "$REPLY" = "a" ]; do
+		while [ "$REPLY" = "a" ]; do
         	search_another_anime
-        done
-        [ "$REPLY" = "q" ] && exit 0
-
-		first_ep_number="0"
+        	done
+        	[ "$REPLY" = "q" ] && exit 0
+		first_ep_number=0
 		result=$(get_dpage_link "$anime_id" "$first_ep_number")
-		if [ -n "$result" ]; then
-			true
-		else
-			first_ep_number="1"
-		fi
+		[ -z "$result" ] && first_ep_number=1
 		;;
 	*)
 		die "Unexpected Scrape type"
@@ -615,7 +588,7 @@ esac
 	open_selection
 
 ########
-# Loop #
+# LOOP #
 ########
 
 while :; do
@@ -625,15 +598,9 @@ if [ -z "$select_first" ]; then
 	else
 		auto_play=0
 	fi
-	if [ "$episode" -ne "$last_ep_number" ]; then
-		menu_line_alternate "next episode" "n"
-	fi
-	if [ "$episode" -ne "$first_ep_number" ]; then
-		menu_line_alternate "previous episode" "p"
-	fi
-	if [ "$last_ep_number" -ne "$first_ep_number" ]; then
-		menu_line_alternate "select episode" "s"
-	fi
+	[ "$episode" -ne "$last_ep_number" ] && menu_line_alternate 'next episode' 'n'
+	[ "$episode" -ne "$first_ep_number" ] && menu_line_alternate 'previous episode' 'p'
+	[ "$last_ep_number" -ne "$first_ep_number" ] && menu_line_alternate 'select episode' 's'
 	menu_line_alternate "replay current episode" "r"
 	menu_line_alternate "search for another anime" "a"
 	menu_line_alternate "search history" "h"
@@ -656,9 +623,9 @@ if [ -z "$select_first" ]; then
 			ep_choice_end=""
 			;;
 
-		s)	episode_selection
+		s)	
+			episode_selection
 			;;
-
 		r)
 			ep_choice_start=$((episode))
 			ep_choice_end=""
@@ -669,13 +636,11 @@ if [ -z "$select_first" ]; then
 		h)
 			search_history
 			;;
-
 		N)
 			ep_choice_start=$((episode + 1))
 			;;
 		q)
 			break;;
-
 		*)
 			tput clear
 			err "invalid choice"
@@ -685,7 +650,6 @@ if [ -z "$select_first" ]; then
 	check_input
 	append_history
 	open_selection
-
 else
 	wait $!
 	exit
