Whitespace fixes

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -286,13 +286,12 @@ anime_selection () {
 		menu_line_strong "exit" "q"
 		prompt "Enter choice"
 		choice="$REPLY $REPLY2"
-        while ! [ "$choice" -eq "$choice" ] 2>/dev/null || [ "$choice" -lt 1 ] || [ "$choice" -ge "$count" ] || [ "$choice" = " " ] ;
-        do
-            [ "$choice" = "q " ] && die
-            err "Invalid choice entered"
-		    prompt "Enter choice"
-		    choice="$REPLY $REPLY2"
-    done
+		while ! [ "$choice" -eq "$choice" ] 2>/dev/null || [ "$choice" -lt 1 ] || [ "$choice" -ge "$count" ] || [ "$choice" = " " ]; do
+			[ "$choice" = "q " ] && die
+			err "Invalid choice entered"
+			prompt "Enter choice"
+			choice="$REPLY $REPLY2"
+		done
 	fi
 	# Select respective anime_id
 	count=1
@@ -322,9 +321,8 @@ episode_selection () {
 			prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
 			ep_choice_start="$REPLY"
 			ep_choice_end="$REPLY2"
-			while [ "$ep_choice_start" -lt "$first_ep_number" ] 2> /dev/null || [ "$ep_choice_end" -gt "$last_ep_number" ] 2> /dev/null || [ "$ep_choice_start" -gt "$last_ep_number" ] 2> /dev/null || [ -z "$ep_choice_start" ] 2> /dev/null
-			do
-				if [ "$ep_choice_end" != -1 ];then
+			while [ "$ep_choice_start" -lt "$first_ep_number" ] 2> /dev/null || [ "$ep_choice_end" -gt "$last_ep_number" ] 2> /dev/null || [ "$ep_choice_start" -gt "$last_ep_number" ] 2> /dev/null || [ -z "$ep_choice_start" ] 2> /dev/null; do
+				if [ "$ep_choice_end" != -1 ]; then
 					err "Invalid number chosen"
 					prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
 					ep_choice_start="$REPLY"
@@ -335,7 +333,7 @@ episode_selection () {
 			ep_choice_start="$ep_choice_to_start" && unset ep_choice_to_start
 		fi
 		whether_half="$(printf '%s' "$ep_choice_start" | cut -c1-1)"
-		if [ "$whether_half" = "h" ];then
+		if [ "$whether_half" = "h" ]; then
 			half_ep=1
 			ep_choice_start="$(printf '%s' "$ep_choice_start" | cut -c2-)"
 		fi
@@ -373,8 +371,7 @@ append_history () {
 
 open_selection() {
 	# opens selected episodes one-by-one
-	for ep in $episodes
-	do
+	for ep in $episodes; do
 		open_episode "$selection_id" "$ep"
 	done
 	episode=${ep_choice_end:-$ep_choice_start}
@@ -397,8 +394,7 @@ open_episode () {
 		episode="$REPLY $REPLY2"
 	done
 	#processing half episodes
-	if [ "$half_ep" -eq 1 ]
-	then
+	if [ "$half_ep" -eq 1 ]; then
 		temp_ep="$episode"
 		episode="${episode}-5"
 	fi
@@ -448,11 +444,11 @@ open_episode () {
 		{
 			#uncomment this below line if you are getting low download speeds, and comment next one after below line
 			#aria2c -x 16 -s 16 --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide &&
-				if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide ;then
-					inf "Downloaded episode: $episode"
-				else
-					err "Download failed episode: $episode , please retry or check your internet connection"
-				fi
+			if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide ; then
+				inf "Downloaded episode: $episode"
+			else
+				err "Download failed episode: $episode , please retry or check your internet connection"
+			fi
 		}
 	fi
 }
@@ -543,7 +539,7 @@ case $scrape in
 			prompt "Search Anime"
 			query="$REPLY $REPLY2"
 		else
-			if [ -n "$ep_choice_to_start" ] ; then
+			if [ -n "$ep_choice_to_start" ]; then
 				REPLY=1
 				select_first=1
 			fi
