complete reimplimentation of the script, scraping 9anim.vip

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,323 +1,225 @@
 #!/bin/sh
 
-# dependencies: grep sed curl video_player
-# video_player ( needs to be able to play urls )
-player_fn="mpv"
+query="$*"
 
-prog="ani-cli"
-logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
-
-c_red="\033[1;31m"
-c_green="\033[1;32m"
-c_yellow="\033[1;33m"
-c_blue="\033[1;34m"
-c_magenta="\033[1;35m"
-c_cyan="\033[1;36m"
-c_reset="\033[0m"
-
-
-help_text () {
-	while IFS= read line; do
-		printf "%s\n" "$line"
-	done <<-EOF
-	USAGE: $prog <query>
-	 -h	 show this help text
-	 -d	 download episode
-	 -H	 continue where you left off
-	EOF
-}
-
+new_line='
+'
+# to trick 9anime that a browser is being used
+curl_headers="
+-H 'authority: 9anim.vip'
+-H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36'
+-H 'referer: https://9anim.vip/serie/1068/sword-art-online.html'
+"
+curl_headers=
+tab_space=$(printf '\t')
 
 die () {
-	printf "$c_red%s$c_reset\n" "$*" >&2
-	exit 1
+	printf '%s\n' "$*" >&2
+	exit 1;
 }
 
-err () {
-	printf "$c_red%s$c_reset\n" "$*" >&2
-}
-
-search_anime () {
-	# get anime name along with its id
-	search=$1
-	titlepattern='<a href="/category/'
-
-	curl -s "https://gogoanime.vc//search.html" \
-		-G \
-		-d "keyword=$search" |
-	sed -n -E '
-		s_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p
-		'
-}
-
-search_eps () {
-	# get available episodes for anime_id
-	anime_id=$1
-
-	curl -s "https://gogoanime.vc/category/$anime_id" |
-	sed -n -E '
-		/^[[:space:]]*<a href="#" class="active" ep_start/{
-		s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
-		q
-		}
-		'
-}
-
-get_links () {
-	# get the download page url
-	anime_id=$1
-	ep_no=$2
-
-	dpage_url=$(
-	curl -s "https://gogoanime.vc/$anime_id-episode-$ep_no" |
-	sed -n -E '
-		/^[[:space:]]*<li class="dowloads">/{
-		s/.*href="([^"]*)".*/\1/p
-		q
-		}')
-
-	curl -s "$dpage_url" |
-	sed -n -E '
-		/^[[:space:]]*href="([^"]*\.mp4)".*/{
-		s/^[[:space:]]*href="([^"]*\.mp4)".*/\1/p
-		q
-		}
-		'
-}
-
-dep_ch () {
-	for dep; do
-		if ! command -v "$dep" >/dev/null ; then
-			die "Program \"$dep\" not found. Please install it."
-		fi
-	done
-}
-
-# get query
-get_search_query () {
-	if [ -z "$*" ]; then
-		printf "Search Anime: "
-		read -r query
-	else
-		query=$*
-	fi
-}
-
-# create history file
-[ -f "$logfile" ] || : > "$logfile"
-
-#####################
-## Anime selection ##
-#####################
-
-anime_selection () {
-	search_results=$*
-	menu_format_string='[%d] %s\n'
-	menu_format_string_c1="$c_blue[$c_cyan%d$c_blue] $c_reset%s\n"
-	menu_format_string_c2="$c_blue[$c_cyan%d$c_blue] $c_yellow%s$c_reset\n"
-
-	count=1
-	while read anime_id; do
-		# alternating colors for menu
-		[ $((count % 2)) -eq 0 ] &&
-			menu_format_string=$menu_format_string_c1 ||
-			menu_format_string=$menu_format_string_c2
-
-		printf "$menu_format_string" "$count" "$anime_id"
-		count=$((count+1))
-	done <<-EOF
-	$search_results
-	EOF
-
-	# User input
-	printf "$c_blue%s$c_green" "Enter number: "
-	read choice
-	printf "$c_reset"
-
-	# Check if input is a number
-	[ "$choice" -eq "$choice" ] 2>/dev/null || die "Invalid number entered"
-
-	# Select respective anime_id
-	count=1
-	while read anime_id; do
-		if [ $count -eq $choice ]; then
-			selection_id=$anime_id
-			break
-		fi
-		count=$((count+1))
-	done <<-EOF
-	$search_results
-	EOF
-
-	[ -z "$selection_id" ] && die "Invalid number entered"
-
-	read last_ep_number <<-EOF
-	$(search_eps "$selection_id")
-	EOF
-}
-
-##################
-## Ep selection ##
-##################
-
-episode_selection () {
-	[ $is_download -eq 1 ] &&
-		printf "Range of episodes can be specified: start_number end_number\n"
-
-	printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
-	read ep_choice_start ep_choice_end
-	printf "$c_reset"
-
-}
-
-open_episode () {
-	anime_id=$1
-	episode=$2
-
-	if [ $episode -lt 1 ] || [ $episode -gt $last_ep_number ]; then
-		err "Episode out of range"
-		printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
-		read episode
-		printf "$c_reset"
-	fi
-
-	printf "Getting data for episode %d\n" $episode
-
-	video_url=$(get_links "$anime_id" "$episode")
-
-	case $video_url in
-		*streamtape*)
-			# If direct download not available then scrape streamtape.com
-			BROWSER=${BROWSER:-firefox}
-			printf "scraping streamtape.com\n"
-			video_url=$(curl -s "$video_url" | sed -n -E '
-				/^<script>document/{
-				s/^[^"]*"([^"]*)" \+ '\''([^'\'']*).*/https:\1\2\&dl=1/p
-				q
-				}
-			');;
-	esac
-
-	if [ $is_download -eq 0 ]; then
-		# write anime and episode number
-		sed -E "
-			s/^${selection_id}\t[0-9]+/${selection_id}\t$((episode+1))/
-		" "$logfile" > "${logfile}.new" && mv "${logfile}.new" "$logfile"
-
-		setsid -f $player_fn "$video_url" >/dev/null 2>&1
-	else
-		printf "Downloading episode $episode ...\n"
-		printf "%s\n" "$video_url"
-		# add 0 padding to the episode name
-		episode=$(printf "%03d" $episode)
-		{
-			curl -L -# -C - "$video_url" -o "${anime_id}-${episode}.mp4" &&
-				printf "${c_green}Downloaded episode: %s${c_reset}\n" "$episode" ||
-				printf "${c_red}Download failed episode: %s${c_reset}\n" "$episode"
-		}
-	fi
-}
-
-############
-# Start Up #
-############
-
-# to clear the colors when exited using SIGINT
-trap "printf '$c_reset'" INT HUP
-
-dep_ch "$player_fn" "curl" "sed" "grep"
-
-# option parsing
-is_download=0
-scrape=query
-while getopts 'hdH' OPT; do
-	case $OPT in
-		h)
-			help_text
-			exit 0
-			;;
-		d)
-			is_download=1
-			;;
-		H)
-			scrape=history
-			;;
-	esac
+##########################
+# PREPARING SEARCH QUERY #
+##########################
+# prepend + before each word, and remove the first words +
+# to get a + separated query
+query_string=
+for word in $query; do
+	query_string=${query_string}+${word}
 done
-shift $((OPTIND - 1))
+query_string=${query_string#+}
 
-########
-# main #
-########
+###########################
+# GETTING THE SEARCH PAGE #
+###########################
+html=$(
+curl -s "https://9anim.vip/search" \
+	-G -d "q=$query_string" $curl_headers
+)
 
-case $scrape in
-	query)
-		get_search_query "$*"
-		search_results=$(search_anime "$query")
-		[ -z "$search_results" ] && die "No search results found"
-		anime_selection "$search_results"
-		episode_selection
+#########################################
+# PARSING AND DISPLAYING THE ANIME LIST #
+#########################################
+anime_url_list=
+anime_count=0
+while IFS= read line; do
+	case $line in
+		'<a href="/serie/'*|'<a href="/movie/'*)
+			anime_count=$((anime_count+1))
+			IFS=\" read _ url _ name _ <<-!
+			$line
+			!
+			# append the anime name and its url to the list
+			anime_url_list=${anime_url_list}${new_line}${url}
+			# print the anime name
+			printf '[%d] %s\n' $anime_count "$name"
+			;;
+		'<span>Dubbed</span>'*)
+			printf '    Dubbed\n'
+	esac
+done<<!
+$html
+!
+anime_url_list=${anime_url_list#$new_line}
+[ $anime_count -eq 0 ] && die "no search results"
+
+##############################
+# SELECTING THE ANIME CHOICE #
+##############################
+read selected_anime_count
+count=0
+while read url; do
+	count=$((count+1))
+	if [ $count -eq $selected_anime_count ]; then
+		selected_anime_url=$url
+	fi
+done<<!
+$anime_url_list
+!
+[ -z "$selected_anime_url" ] && die "invalid choice"
+
+##########################
+# GETTING THE ANIME PAGE #
+##########################
+
+play_ep () {
+	html=$(
+		curl -s "https://9anim.vip/ajax/${ep_type}/downloads/${ep_id}.html" \
+			-H 'authority: 9anim.vip' \
+			-H 'accept: */*' \
+			-H 'x-requested-with: XMLHttpRequest' \
+			-H 'sec-gpc: 1' \
+			-H 'sec-fetch-site: same-origin' \
+			-H 'sec-fetch-mode: cors' \
+			-H 'sec-fetch-dest: empty' \
+			-H "referer: ${selected_anime_url}" \
+			-H 'accept-language: en-US,en;q=0.9' \
+			--compressed
+	)
+	flag=0
+	while read line; do
+		case $line in
+			'<td>'*)
+				if [ $flag -eq 0 ]; then
+					name=${name#<td>}
+					name=${line%%<*}
+					flag=1
+				fi
+				;;
+			'<a'*)
+				flag=0
+				url=${line#*href=\"}
+				url=${url%%\"*}
+				echo "$name"
+				echo "$url"
+				;;
+		esac
+	done<<-!
+	$html
+	!
+	mpv "$url"
+}
+
+case $selected_anime_url in
+	'/movie/'*)
+		ep_id=${selected_anime_url#/movie/}
+		ep_id=${ep_id%%/*}
+		ep_type=movie
+		play_ep
 		;;
-	history)
-		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
-		[ -z "$search_results" ] && die "History is empty"
-		anime_selection "$search_results"
-		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+	'/serie/'*)
+		####################
+		# SEASON SELECTION #
+		####################
+		html=$(
+		curl -s "https://9anim.vip$selected_anime_url"
+		)
+		series_id=
+		anime_count=0
+		while IFS= read line; do
+			case $line in
+				'<button class="dropdown-item'*)
+					anime_count=$((anime_count+1))
+					alt_number=${line#*alt=\"}
+					alt_number=${alt_number%%\"*}
+					season_name=${line%<*}
+					season_name=${season_name##*>}
+					series_id=${series_id}${new_line}${alt_number}
+
+					printf '[%d] %s\n' $anime_count "$season_name"
+					;;
+			esac
+		done<<-!
+		$html
+		!
+		series_id=${series_id#$new_line}
+
+		read selected_season_count
+		count=0
+		while read id; do
+			count=$((count+1))
+			if [ $count -eq $selected_season_count ]; then
+				selected_season_id=$id
+			fi
+		done<<-!
+		$series_id
+		!
+		[ -z "$selected_season_id" ] && die "invalid choice"
+
+		#####################
+		# Episode SELECTION #
+		#####################
+		html=$(
+		curl -s "https://9anim.vip/ajax/episodes/${selected_season_id}.html" \
+		  -H 'authority: 9anim.vip' \
+		  -H 'accept: */*' \
+		  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
+		  -H 'x-requested-with: XMLHttpRequest' \
+		  -H 'sec-gpc: 1' \
+		  -H 'sec-fetch-site: same-origin' \
+		  -H 'sec-fetch-mode: cors' \
+		  -H 'sec-fetch-dest: empty' \
+		  -H "referer: $selected_anime_url" \
+		  -H 'accept-language: en-US,en;q=0.9' \
+		  --compressed
+		)
+
+		ep_ids=
+		anime_count=0
+		while read line; do
+			case $line in
+				'<button class='*)
+					anime_count=$((anime_count+1))
+					data_id=${line#*'data-id='}
+					data_id=${data_id%% *}
+
+					data_title=${line#*'data-title="'}
+					data_title=${data_title%%\"*}
+
+					ep_ids=${ep_ids}${new_line}${data_id}
+
+					printf '[%d] %s\n' $anime_count "$data_title"
+					;;
+			esac
+		done<<-!
+		$html
+		!
+		ep_ids=${ep_ids#$new_line}
+		read selected_episode_count
+
+		count=0
+		while read id; do
+			count=$((count+1))
+			if [ $count -eq $selected_episode_count ]; then
+				selected_episode_id=$id
+			fi
+		done<<-!
+		$ep_ids
+		!
+		[ -z "$selected_episode_id" ] && die "invalid choice"
+
+		ep_id=$selected_episode_id
+		ep_type=serie
+		play_ep
 		;;
 esac
-
-
-{ # checking input
-	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
-	episodes=$ep_choice_start
-
-	if [ -n "$ep_choice_end" ]; then
-		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die "Invalid number entered"
-		# create list of episodes to download/watch
-		episodes=$(seq $ep_choice_start $ep_choice_end)
-	fi
-}
-
-# add anime to history file
-grep -q -w "${selection_id}" "$logfile" ||
-	printf "%s\t%d\n" "$selection_id" $((episode+1)) >> "$logfile"
-
-for ep in $episodes
-do
-	open_episode "$selection_id" "$ep"
-done
-episode=${ep_choice_end:-$ep_choice_start}
-
-while :; do
-	printf "\n${c_green}Currently playing %s episode ${c_cyan}%d/%d\n" "$selection_id" $episode $last_ep_number
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "n" "next episode"
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_magenta%s$c_reset\n" "p" "previous episode"
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_yellow%s$c_reset\n" "s" "select episode"
-	printf "$c_blue[${c_cyan}%s$c_blue] $c_red%s$c_reset\n" "q" "exit"
-	printf "${c_blue}Enter choice:${c_green} "
-	read choice
-	printf "$c_reset"
-	case $choice in
-		n)
-			episode=$((episode + 1))
-			;;
-		p)
-			episode=$((episode - 1))
-			;;
-
-		s)	printf "${c_blue}Choose episode $c_cyan[1-%d]$c_reset:$c_green " $last_ep_number
-			read episode
-			printf "$c_reset"
-			[ "$episode" -eq "$episode" ] 2>/dev/null || die "Invalid number entered"
-			;;
-
-		q) 
-			break;;
-
-		*)
-			die "invalid choice"
-			;;
-	esac
-
-	open_episode "$selection_id" "$episode"
-done
