Initial commit

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -42,7 +42,7 @@ search_anime () {
 	search=$(printf '%s' "$1" | tr ' ' '-' )
 	titlepattern='<a href="/category/'
 
-	curl -s "https://gogoanime.vc//search.html" \
+	curl -s "https://gogoanime.pe//search.html" \
 		-G \
 		-d "keyword=$search" |
 	sed -n -E '
@@ -54,7 +54,7 @@ search_eps () {
 	# get available episodes for anime_id
 	anime_id=$1
 
-	curl -s "https://gogoanime.vc/category/$anime_id" |
+	curl -s "https://gogoanime.pe/category/$anime_id" |
 	sed -n -E '
 		/^[[:space:]]*<a href="#" class="active" ep_start/{
 		s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
@@ -69,7 +69,7 @@ get_embedded_video_link() {
 	ep_no=$2
 
 	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
-	curl -s "https://gogoanime.vc/$anime_id-episode-$ep_no" |
+	curl -s "https://gogoanime.pe/$anime_id-episode-$ep_no" |
 	sed -n -E '
 		/^[[:space:]]*<a href="#" rel="100"/{
 		s/.*data-video="([^"]*)".*/https:\1/p
@@ -77,15 +77,42 @@ get_embedded_video_link() {
 		}'
 }
 
+get_video_quality() {
+	# If quailty is -1 get the highest quailty available
+	video_file="$1"
+	if [ $quality -eq -1 ]; then
+		printf '%s' "$video_file" | sed -n -E 's/.*NAME="([^p]*)p"/\1/p' | tail -n 1
+	else
+		# is current quality available
+		is_quality_avail=$(printf '%s' "$video_file" | sed -n -E "s/.*NAME=\"($quality\p)\"/\1/p")
+		video_quality="$quality"
+
+		if [ -z "$is_quality_avail" ]; then
+			printf "$c_red%s$c_reset\n" "Current video quality is not available (defaulting to highest quality)" >&2
+
+			quality=-1
+			video_quality=$(printf '%s' "$video_file" | sed -n -E 's/.*NAME="([^p]*)p"/\1/p' | tail -n 1)
+		fi
+
+		printf '%s' "$video_quality"
+	fi
+}
+
 get_links () {
 	embedded_video_url="$1"
-	curl -s "$embedded_video_url" |
+	video_url=$(curl -s "$embedded_video_url" |
 	sed -n -E '
 		/^[[:space:]]*sources:/{
 		s/.*(https[^'\'']*).*/\1/p
 		q
 		}
-		'
+		')
+
+	video_file=$(curl -s --referer "$embedded_video_url" "$video_url")
+	video_quality=$(get_video_quality "$video_file")
+
+	# Replace the video with highest quality video
+	printf '%s' "$video_url" | sed -n -E "s/(.*)\.m3u8/\1.$video_quality.m3u8/p"
 }
 
 dep_ch () {
@@ -177,7 +204,7 @@ open_episode () {
 	anime_id=$1
 	episode=$2
 
-	# Cool effect way of clearing screen
+	# Cool way of clearing screen
 	printf '\x1B[2J\x1B[1;1H'
 	if [ $episode -lt 1 ] || [ $episode -gt $last_ep_number ]; then
 		err "Episode out of range"
@@ -236,8 +263,9 @@ dep_ch "$player_fn" "curl" "sed" "grep"
 
 # option parsing
 is_download=0
+quality=-1
 scrape=query
-while getopts 'hdH' OPT; do
+while getopts 'hdHq:' OPT; do
 	case $OPT in
 		h)
 			help_text
@@ -248,6 +276,9 @@ while getopts 'hdH' OPT; do
 			;;
 		H)
 			scrape=history
+			;;
+		q)
+			quality=$OPTARG
 			;;
 	esac
 done
@@ -273,6 +304,7 @@ case $scrape in
 		;;
 esac
 
+[ "$quality" -eq "$quality" ] 2>/dev/null || die "Invalid number entered"
 
 { # checking input
 	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
