feat: argument parsing
+ I possibly fucked up a merge conflict regarding quality parsing.
+ Please check if issues arise
+ refactor: folded single-line cases into one line
+ fix: show error if no results are found
+ fix: windows
+ docs: updated dependencies
+ docs: iamchokerman --> justchokingaround

Co-authored-by: port19 <port19@port19.xyz>
Co-authored-by: Derisis13 <email.felhasznalasra@gmail.com>
Co-authored-by: CoolnsX <ansari.tan20@gmail.com>
Co-authored-by: chokerman <44473782+justchokingaround@users.noreply.github.com>
Co-authored-by: zenith71 <71zenith@protonmail.com>

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -26,6 +26,18 @@ die() {
 	exit 1
 }
 
+help_info () {
+	die "To be implemented"
+}
+
+version_info () {
+	die "To be implemented"
+}
+
+update_script () {
+	die "To be implemented"
+}
+
 
 # SCRAPING
 
@@ -52,9 +64,7 @@ get_links() {
 			curl -s "$extract_link" -A "$agent" | sed 's|^#.*x||g; s|,.*|p|g; /^#/d; $!N; s|\n| >|' | sed "s|>|>${relative_link}|g" | sort -nr
 		fi
 		;;
-	*)
-		[ -n "$episode_link" ] && printf "%s\n" "$episode_link"
-		;;
+	*) [ -n "$episode_link" ] && printf "%s\n" "$episode_link" ;;
 	esac
 	printf "Fetching %s Links\n" "$provider_name" 1>&2
 }
@@ -68,26 +78,11 @@ provider_init() {
 # generates links based on given provider
 generate_link() {
 	case $1 in
-	1)
-		# vrv,wixmp(default)(m3u8)(multi) -> (mp4)(multi)
-		provider_init 'vrv|wixmp' '/Default :/p'
-		;;
-	2)
-		# pstatic(default backup)(mp4)(multi)
-		provider_init 'pstatic' '/Default B :/p'
-		;;
-	3)
-		# sharepoint(mp4)(single)
-		provider_init 'sharepoint' '/S-mp4 :/p'
-		;;
-	4)
-		# usercloud(mp4)(single)
-		provider_init 'usercloud' '/Uv-mp4 :/p'
-		;;
-	*)
-		# gogoanime(m3u8)(multi)
-		provider_init 'gogoanime' '/Luf-mp4 :/p'
-		;;
+	1) provider_init 'vrv|wixmp' '/Default :/p' ;;	# vrv,wixmp(default)(m3u8)(multi) -> (mp4)(multi)
+	2) provider_init 'pstatic' '/Default B :/p' ;;	# pstatic(default backup)(mp4)(multi)
+	3) provider_init 'sharepoint' '/S-mp4 :/p' ;;		# sharepoint(mp4)(single)
+	4) provider_init 'usercloud' '/Uv-mp4 :/p' ;;		# usercloud(mp4)(single)
+	*) provider_init 'gogoanime' '/Luf-mp4 :/p' ;;	# gogoanime(m3u8)(multi)
 	esac
 	# logic yet to implement
 	[ -n "$provider_id" ] && get_links "$provider_id"
@@ -96,23 +91,9 @@ generate_link() {
 select_quality () {
 	links=$(cat "$cache_dir"/* | sed 's|^Mp4-||g' | sort -g -r -s)
 	case "$1" in
-	best)
-		result=$(cat "$cache_dir"/* | head -n1)
-		for qual in 1080 720 480 360 240 144; do
-			result_fixed=$(cat "$cache_dir"/* | grep -m 1 "$qual")
-			[ -n "$result_in" ] && result="$result_fixed" && break
-		done
-		;;
-	worst)
-		result=$(cat "$cache_dir"/* | tail -n1)
-		for qual in 144 270 360 480 720 1080; do
-			result_fixed=$(cat "$cache_dir"/* | grep -m 1 "$qual")
-			[ -n "$result_in" ] && result="$result_fixed" && break
-		done
-		;;
-	*)
-		result=$(printf "%s" "$links" | grep -m 1 "$1")
-		;;
+	best) result=$(printf "%s" "$links" | head -n1) ;;
+	worst) result=$(printf "%s" "$links" | grep -E '^[0-9]{3,4}' | tail -n1) ;;
+	*) result=$(printf "%s" "$links" | grep -m 1 "$1") ;;
 	esac
 	[ -z "$result" ] && printf "Specified quality not found, defaulting to best" 1>&2 && result=$(cat "$cache_dir"/* | head -n1)
 	printf "%s" "$result" | cut -d'>' -f2
@@ -138,7 +119,7 @@ get_episode_url() {
 
 # search the query and give results
 search_anime() {
-	curl -s "https://allanime.site/allanimeapi?variables=%7B%22search%22%3A%7B%22allowAdult%22%3Atrue%2C%22allowUnknown%22%3Atrue%2C%22query%22%3A%22$*%22%7D%2C%22limit%22%3A40%2C%22page%22%3A1%2C%22translationType%22%3A%22$mode%22%2C%22countryOrigin%22%3A%22ALL%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%229c7a8bc1e095a34f2972699e8105f7aaf9082c6e1ccd56eab99c2f1a971152c6%22%7D%7D" -A "$agent" | sed 's|Show|\n|g' | sed -nE "s|.*_id\":\"([^\"]*)\",\"name\":\"([^\"]*)\".*\"$mode\":([1-9][^,]*).*|\1\t\2 (\3 episode)|p"
+	wget -q -O - "https://allanime.site/allanimeapi?variables=%7B%22search%22%3A%7B%22allowAdult%22%3Atrue%2C%22allowUnknown%22%3Atrue%2C%22query%22%3A%22$*%22%7D%2C%22limit%22%3A40%2C%22page%22%3A1%2C%22translationType%22%3A%22$mode%22%2C%22countryOrigin%22%3A%22ALL%22%7D&extensions=%7B%22persistedQuery%22%3A%7B%22version%22%3A1%2C%22sha256Hash%22%3A%229c7a8bc1e095a34f2972699e8105f7aaf9082c6e1ccd56eab99c2f1a971152c6%22%7D%7D" -U "$agent" | sed 's|Show|\n|g' | sed -nE "s|.*_id\":\"([^\"]*)\",\"name\":\"([^\"]*)\".*\"$mode\":([1-9][^,]*).*|\1\t\2 (\3 episode)|p"
 }
 
 # get the episodes list of the selected anime
@@ -151,37 +132,20 @@ episodes_list() {
 
 download () {
 	case $1 in
-	*m3u8*)
-		ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4" ;;
-	*)
-		aria2c --check-certificate=false --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
+	*m3u8*) ffmpeg -loglevel error -stats -i "$1" -c copy "$download_dir/$2.mp4" ;;
+	*) aria2c --check-certificate=false --summary-interval=0 -x 16 -s 16 "$1" --dir="$download_dir" -o "$2.mp4" --download-result=hide ;;
 	esac
 }
 
 play_episode() {
 	get_episode_url
-	#play the episode
 	case "$player_function" in
-	debug)
-		printf "All links:\n"
-		cat "$cache_dir"/*
-		printf "Selected link:\n%s\n" "$episode"
-		;;
-	mpv | iina)
-		nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1 &
-		;;
-	vlc)
-		nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1 &
-		;;
-	syncplay)
-		nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" > /dev/null 2>&1 &
-		;;
-	download)
-		"$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}"
-		;;
-	*)
-		die "Invalid player function"
-		;;
+	debug) printf "All links:\n%s\nSelected link:\n%s\n" "$links" "$episode" ;;
+	mpv | iina) nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1 & ;;
+	vlc) nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" > /dev/null 2>&1 & ;;
+	syncplay) nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" > /dev/null 2>&1 & ;;
+	download) "$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}" ;;
+	*) die "Invalid player function" ;;
 	esac
 	[ "$use_external_menu" = "1" ] && wait
 }
@@ -201,16 +165,43 @@ cache_dir="${ANI_CLI_CACHE_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/ani-cli}"
 [ ! -d "$cache_dir" ] && mkdir -p "$cache_dir"
 hist_dir="${ANI_CLI_HIST_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/ani-cli}"
 [ ! -d "$hist_dir" ] && mkdir -p "$hist_dir"
+search="${ANI_CLI_DEFAULT_SOURCE:-scrape}"
+
+while getopts ":vdsq:c-:" option ; do
+	case "$option" in
+	v) player_function=vlc ;;
+	d) player_function=download ;;
+	s) player_function=syncplay ;;
+	c) search=history ;;
+	q) quality="$OPTARG" ;;
+	-)
+		case "$OPTARG" in
+		version) version_info ;;
+		help) help_info ;;
+		update) update_script ;;
+		*) die "Unknown option!" ;;
+		esac
+		;;
+	*) die "Unknown option!" ;;
+	esac
+done
+shift $(( OPTIND - 1 ))
 
 # searching
-query="$*"
-while [ -z "$query" ]; do
-	printf "Search anime\n>> "
-	read -r query
-done
-query=$(printf "%s" "$query" | sed "s| |%20|g")
-anime_list=$(search_anime "$query")
-result=$(printf "%s" "$anime_list" | nth "Select anime: ") || exit 1
+case "$search" in
+history) die "Not implemented yet!" ;;
+*)
+	query="$*"
+	while [ -z "$query" ]; do
+		printf "Search anime\n>> "
+		read -r query
+	done
+	query=$(printf "%s" "$query" | sed "s| |%20|g")
+	anime_list=$(search_anime "$query")
+	[ -z "$anime_list" ] && die "No results found!"
+	result=$(printf "%s" "$anime_list" | nth "Select anime: ") || exit 1
+	;;
+esac
 title=$(printf "%s" "$result" | cut -f2)
 allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]' | tr 'A-Z ' 'a-z-')"
 id=$(printf "%s" "$result" | cut -f1)
@@ -221,19 +212,11 @@ ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") || exit 1
 play_episode
 while cmd=$(printf "quit\nselect\nprevious\nreplay\nnext" | nth "Playing episode $ep_no of $title... "); do
 	case "$cmd" in
-	previous)
-		ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{n;p;}") 2>/dev/null
-		;;
+	previous) ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{n;p;}") 2>/dev/null ;;
 	replay) ;;
-	next)
-		ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{g;1!p;};h") 2>/dev/null
-		;;
-	select)
-		ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ")
-		;;
-	*)
-		exit 0
-		;;
+	next) ep_no=$(printf "%s" "$ep_list" | sed -n "|^${ep_no}$|{g;1!p;};h") 2>/dev/null ;;
+	select) ep_no=$(printf "%s" "$ep_list" | nth "Select episode: ") ;;
+	*) exit 0 ;;
 	esac
 	[ -z "$ep_no" ] && die "Out of range"
 	play_episode
