Added `"`-s where they weren't, but "$" was. Replaced `"`-s with `'`-s when it made sense.

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 # version number
-VERSION="1.6.4"
+VERSION='1.6.4'
 
 
 # history file path
 logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
-auto_play=0
+auto_play="0"
 
 #######################
 # Auxiliary functions #
@@ -14,7 +14,7 @@ auto_play=0
 
 help_text () {
 	while IFS= read -r line; do
-		printf "%s\n" "$line"
+		printf '%s\n' "$line"
 	done <<-EOF
 
 	Usage:
@@ -59,10 +59,10 @@ update_script () {
 	# get the newest version of this script from github and replace it
 	update="$(curl -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli" | diff -u "$0" -)"
 	if [ -z "$update" ]; then
-		inf "Script is up to date :)"
+		inf 'Script is up to date :)'
 	else
 		if printf '%s\n' "$update" | patch "$0" - ; then
-			inf "Script has been updated"
+			inf 'Script has been updated'
 		else
 			die "Can't update for some reason!"
 		fi
@@ -75,8 +75,8 @@ dep_ch () {
 		if ! command -v "$dep" >/dev/null ; then
 			err "Program \"$dep\" not found. Please install it."
 			#aria2c is in the package aria2
-			if [ "$dep" = "aria2c" ]; then
-				err "To install aria2c, Type <your_package_manager> aria2"
+			if [ "$dep" = 'aria2c' ]; then
+				err 'To install aria2c, Type <your_package_manager> aria2'
 			fi
 			die
 		fi
@@ -117,7 +117,7 @@ search_for_unwatched () {
 	# compares history with gogoanime, only shows unfinished anime
 	search_results=$*
 
-	unwatched_anime=""
+	unwatched_anime=''
 	while read -r anime_id; do
 		current_ep_number="$(search_eps "$anime_id")"
 		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
@@ -131,28 +131,28 @@ search_for_unwatched () {
 	$search_results
 	EOF
 	if [ -z "$unwatched_anime" ]; then
-		die "No unwatched episodes"
+		die 'No unwatched episodes'
 	fi
-	printf "%s" "$unwatched_anime"
+	printf '%s' "$unwatched_anime"
 }
 
 search_another_anime () {
 	tput clear
-	prompt "Search Anime"
+	prompt 'Search Anime'
 	query="$REPLY $REPLY2"
-	search_results=$(search_anime "$query")
-	[ -z "$search_results" ] && die "No search results found"
+	search_results="$(search_anime "$query")"
+	[ -z "$search_results" ] && die 'No search results found'
 	anime_selection "$search_results"
 	episode_selection
 }
 
 search_history () {
 	tput clear
-	search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
-	[ -z "$search_results" ] && die "History is empty"
-	search_results=$(search_for_unwatched "$search_results")
+	search_results="$(sed -n -E 's/\t[0-9]*//p' "$logfile")"
+	[ -z "$search_results" ] && die 'History is empty'
+	search_results="$(search_for_unwatched "$search_results")"
 	anime_selection "$search_results"
-	ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+	ep_choice_start="$(sed -n -E "s/${selection_id}\t//p" "$logfile")"
 }
 
 ##################
@@ -161,15 +161,15 @@ search_history () {
 
 get_dpage_link() {
 	# get the download page url
-	anime_id=$1
-	ep_no=$2
+	anime_id="$1"
+	ep_no="$2"
 
 	# credits to fork: https://github.com/Dink4n/ani-cli for the fix
 	# dub prefix takes the value "-dub" when dub is needed else is empty
-	anime_page=$(curl -s "$base_url/$anime_id-$ep_no")
+	anime_page="$(curl -s "$base_url/$anime_id-$ep_no")"
 
-	if printf '%s' "$anime_page" | grep -q "404" ; then
-		anime_page=$(curl -s "$base_url/$anime_id-episode-$ep_no")
+	if printf '%s' "$anime_page" | grep -q '404' ; then
+		anime_page="$(curl -s "$base_url/$anime_id-episode-$ep_no")"
 	fi
 
 	printf '%s' "$anime_page" |
@@ -197,22 +197,22 @@ decrypt_link() {
 get_video_quality() {
 	# chooses the link for the set quality
 	dpage_url="$1"
-	video_links=$(decrypt_link "$dpage_url")
-	case $quality in
+	video_links="$(decrypt_link "$dpage_url")"
+	case "$quality" in
 		best)
-			video_link=$(printf '%s' "$video_links" | head -n 4 | tail -n 1)
+			video_link="$(printf '%s' "$video_links" | head -n 4 | tail -n 1)"
 			;;
 
 		worst)
-			video_link=$(printf '%s' "$video_links" | head -n 1)
+			video_link="$(printf '%s' "$video_links" | head -n 1)"
 			;;
 
 		*)
-			video_link=$(printf '%s' "$video_links" | grep -i "${quality}p" | head -n 1)
+			video_link="$(printf '%s' "$video_links" | grep -i "${quality}p" | head -n 1)"
 			if [ -z "$video_link" ]; then
-				err "Current video quality is not available (defaulting to best quality)"
+				err 'Current video quality is not available (defaulting to best quality)'
 				quality=best
-				video_link=$(printf '%s' "$video_links" | head -n 4 | tail -n 1)
+				video_link="$(printf '%s' "$video_links" | head -n 4 | tail -n 1)"
 			fi
 			;;
 	esac
@@ -226,32 +226,32 @@ get_video_quality() {
 
 err () {
 	# display an error message to stderr (in red)
-	printf "\033[1;31m%s\033[0m\n" "$*" >&2
+	printf '\033[1;31m%s\033[0m\n' "$*" >&2
 }
 
 inf () {
 	# display an informational message (first argument in green, second in magenta)
-	printf "\033[1;32m%s \033[1;35m%s\033[0m\n" "$1" "$2"
+	printf '\033[1;32m%s \033[1;35m%s\033[0m\n' "$1" "$2"
 }
 
 prompt () {
         # prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
-        printf "\033[1;34m%s\033[1;35m%s\033[1;34m: \033[0m" "$1" "$2"
+        printf '\033[1;34m%s\033[1;35m%s\033[1;34m: \033[0m' "$1" "$2"
         read -r REPLY REPLY2
 }
 
 menu_line_even () {
 	# displays an even (cyan) line of a menu line with $2 as an indicator in [] and $1 as the option
-	printf "\033[1;34m[\033[1;36m%s\033[1;34m] \033[1;36m%s\033[0m\n" "$2" "$1"
+	printf '\033[1;34m[\033[1;36m%s\033[1;34m] \033[1;36m%s\033[0m\n' "$2" "$1"
 }
 
 menu_line_odd() {
 	# displays an odd (yellow) line of a menu line with $2 as an indicator in [] and $1 as the option
-	printf "\033[1;34m[\033[1;33m%s\033[1;34m] \033[1;33m%s\033[0m\n" "$2" "$1"
+	printf '\033[1;34m[\033[1;33m%s\033[1;34m] \033[1;33m%s\033[0m\n' "$2" "$1"
 }
 
 menu_line_alternate() {
-	menu_line_parity=${menu_line_parity:-0}
+	menu_line_parity="${menu_line_parity:-0}"
 
 	if [ "$menu_line_parity" -eq 0 ]; then
 		menu_line_odd "$1" "$2"
@@ -264,7 +264,7 @@ menu_line_alternate() {
 
 menu_line_strong() {
 	# displays a warning (red) line of a menu line with $2 as an indicator in [] and $1 as the option
-	printf "\033[1;34m[\033[1;31m%s\033[1;34m] \033[1;31m%s\033[0m\n" "$2" "$1"
+	printf '\033[1;34m[\033[1;31m%s\033[1;34m] \033[1;31m%s\033[0m\n' "$2" "$1"
 }
 
 
@@ -273,39 +273,39 @@ menu_line_strong() {
 #################
 
 anime_selection () {
-	count=1
+	count="1"
 	while read -r anime_id; do
 		menu_line_alternate "$anime_id" "$count"
-		: $((count+=1))
+		: "$((count+=1))"
 	done <<-EOF
 	$search_results
 	EOF
 	if [ -n "$ep_choice_to_start" ] && [ -n "$select_first" ]; then
 		tput clear
-		choice=1
+		choice="1"
 	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
-        menu_line_alternate "search for another anime" "a"
-        menu_line_strong "exit" "q"
-		prompt "Enter choice"
+        menu_line_alternate 'search for another anime' 'a'
+        menu_line_strong 'exit' 'q'
+		prompt 'Enter choice'
 		choice="$REPLY $REPLY2"
 	fi
 
 		# Check if input is a number
 		[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
 		# Select respective anime_id
-		count=1
+		count="1"
 		while read -r anime_id; do
 			if [ "$count" -eq "$choice" ]; then
-				selection_id=$anime_id
+				selection_id="$anime_id"
 				break
 			fi
-			count=$((count+1))
+			count="$((count+1))"
 		done <<-EOF
 		$search_results
 		EOF
 
 	if [ -z "$selection_id" ]; then
-		die "Invalid number entered"
+		die 'Invalid number entered'
 	fi
 
 	search_ep_result="$(search_eps "$selection_id")"
@@ -317,7 +317,7 @@ anime_selection () {
 episode_selection () {
 	# using get_dpage_link to get confirmation from episode 0 if it exists,else first_ep_number becomes "1"
 	first_ep_number="0"
-	result=$(get_dpage_link "$anime_id" "$first_ep_number")
+	result="$(get_dpage_link "$anime_id" "$first_ep_number")"
 
 	if [ -n "$result" ]; then
 		true
@@ -327,30 +327,30 @@ episode_selection () {
 
 	if [ "$last_ep_number" -gt "$first_ep_number" ]; then
 
-		inf "Range of episodes can be specified: start_number end_number"
+		inf 'Range of episodes can be specified: start_number end_number'
 
 		if [ -z "$ep_choice_to_start" ]; then
-			prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
-			ep_choice_start=$REPLY
-			ep_choice_end=$REPLY2
+			prompt 'Choose episode' "[$first_ep_number-$last_ep_number]"
+			ep_choice_start="$REPLY"
+			ep_choice_end="$REPLY2"
 		else
-			ep_choice_start=$ep_choice_to_start && unset ep_choice_to_start
+			ep_choice_start="$ep_choice_to_start" && unset ep_choice_to_start
 		fi
 		whether_half="$(echo "$ep_choice_start" | cut -c1-1)"
 		if [ "$whether_half" = "h" ]
 		then
-			half_ep=1
+			half_ep="1"
 			ep_choice_start="$(echo "$ep_choice_start" | cut -c2-)"
 		fi
 	else
 		# In case the anime contains only a single episode
-		ep_choice_start=1
+		ep_choice_start="1"
 	fi
 
 	if [ -z "$ep_choice_end" ]; then
-		auto_play=0
+		auto_play="0"
 	else
-		auto_play=1
+		auto_play="1"
 		[ "$ep_choice_end" = "-1" ] && ep_choice_end="$last_ep_number"
 	fi
 
@@ -359,12 +359,12 @@ episode_selection () {
 
 check_input() {
 	# checks if input is number, creates $episodes from $ep_choice_start and $ep_choice_end
-	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
-	episodes=$ep_choice_start
+	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die 'Invalid number entered'
+	episodes="$ep_choice_start"
 	if [ -n "$ep_choice_end" ]; then
-		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die "Invalid number entered"
+		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die 'Invalid number entered'
 		# create list of episodes to download/watch
-		episodes=$(seq "$ep_choice_start" "$ep_choice_end")
+		episodes="$(seq "$ep_choice_start" "$ep_choice_end")"
 	fi
 }
 
@@ -375,49 +375,49 @@ check_input() {
 
 append_history () {
 	grep -q -w "${selection_id}" "$logfile" ||
-		printf "%s\t%d\n" "$selection_id" $((episode+1)) >> "$logfile"
+		printf '%s\t%d\n' "$selection_id" "$((episode+1))" >> "$logfile"
 }
 
 open_selection() {
 	# opens selected episodes one-by-one
-	for ep in $episodes
+	for ep in "$episodes"
 	do
 		open_episode "$selection_id" "$ep"
 	done
-	episode=${ep_choice_end:-$ep_choice_start}
+	episode="${ep_choice_end:-$ep_choice_start}"
 }
 
 open_episode () {
-	anime_id=$1
-	episode=$2
+	anime_id="$1"
+	episode="$2"
 	# Cool way of clearing screen
 	tput clear
 	# checking if episode is in range
 	while  [ "$episode" -gt "$last_ep_number" ] || [ -z "$episode"  ]
 	do
-		[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
+		[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die 'Invalid number entered'
 		if [ "$last_ep_number" -eq 0 ]; then
-			die "Episodes not released yet!"
+			die 'Episodes not released yet!'
 		else
-			err "Episode out of range"
+			err 'Episode out of range'
 		fi
-		prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
+		prompt 'Choose episode' "[$first_ep_number-$last_ep_number]"
 		episode="$REPLY $REPLY2"
 	done
 	#processing half episodes
 	if [ "$half_ep" -eq 1 ]
 	then
-		temp_ep=$episode
-		episode=$episode"-5"
+		temp_ep="$episode"
+		episode="$episode'-5'"
 	fi
 
 	inf "Getting data for episode $episode"
 	# decrypting url
-	dpage_link=$(get_dpage_link "$anime_id" "$episode")
-	video_url=$(get_video_quality "$dpage_link")
+	dpage_link="$(get_dpage_link "$anime_id" "$episode")"
+	video_url="$(get_video_quality "$dpage_link")"
 	if [ "$half_ep" -eq 1 ]; then
-		episode=$temp_ep
-		half_ep=0
+		episode="$temp_ep"
+		half_ep="0"
 	fi
 	# Download or play episodes
 	if [ "$is_download" -eq 0 ]; then
@@ -429,12 +429,12 @@ open_episode () {
 		kill "$PID" >/dev/null 2>&1
 
 		if [ -z "$video_url" ]; then
-			die "Video URL not found"
+			die 'Video URL not found'
 		fi
 
 
 
-		case $player_fn in
+		case "$player_fn" in
 			vlc)
 				if [ "$auto_play" -eq 0 ]; then
 					nohup "$player_fn" --http-referrer="$dpage_link" "$video_url" > /dev/null 2>&1 &
@@ -454,14 +454,14 @@ open_episode () {
 				fi
 				;;
 		esac
-		PID=$!
+		PID="$!"
 
 		mv "${logfile}.new" "$logfile"
 	else
 		mkdir -p "$download_dir"
 		inf "Downloading episode $episode ...\n"
 		# add 0 padding to the episode name
-		episode=$(printf "%03d" "$episode")
+		episode=$(printf '%03d' "$episode")
 		{
 		    #uncomment this below line if you are getting low download speeds, and comment next one after below line
 			#aria2c -x 16 -s 16 --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide &&
@@ -486,12 +486,12 @@ trap 'printf "\033[0m"; exit 1' INT HUP
 
 # default options
 player_fn="mpv" #video player needs to be able to play urls
-is_download=0
-half_ep=0
-quality=best
-scrape=query
-download_dir="."
-choice=""
+is_download='0'
+half_ep='0'
+quality='best'
+scrape='query'
+download_dir='.'
+choice=''
 
 while getopts 'viq:dp:chDUVa:' OPT; do
 	case $OPT in
@@ -500,27 +500,27 @@ while getopts 'viq:dp:chDUVa:' OPT; do
 			exit 0
 			;;
 		d)
-			is_download=1
+			is_download='1'
 			;;
 		a)
-			ep_choice_to_start=$OPTARG
+			ep_choice_to_start="$OPTARG"
 			;;
 		D)
 			: > "$logfile"
 			exit 0
 			;;
 		p)
-			is_download=1
-			download_dir=$OPTARG
+			is_download='1'
+			download_dir="$OPTARG"
 			;;
 		i)
-			player_fn="iina"
+			player_fn='iina'
 			;;
 		q)
-			quality=$OPTARG
+			quality="$OPTARG"
 			;;
 		c)
-			scrape=history
+			scrape="history"
 			;;
 		v)
 			player_fn="vlc"
@@ -541,53 +541,53 @@ while getopts 'viq:dp:chDUVa:' OPT; do
 done
 
 # check for main dependencies
-dep_ch "curl" "sed" "grep" "git" "openssl"
+dep_ch 'curl' 'sed' 'grep' 'git' 'openssl'
 
 # check for optional dependencies
 if [ "$is_download" -eq 0 ]; then
     dep_ch "$player_fn"
 else
-	dep_ch "aria2c"
+	dep_ch 'aria2c'
 fi
 
-shift $((OPTIND - 1))
+shift "$((OPTIND - 1))"
 # gogoanime likes to change domains but keep the olds as redirects
-base_url=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm)
-case $scrape in
+base_url="$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm)"
+case "$scrape" in
 	query)
 		if [ -z "$*" ]; then
-			prompt "Search Anime"
+			prompt 'Search Anime'
 			query="$REPLY $REPLY2"
 		else
-			[ -n "$ep_choice_to_start" ] && select_first=1
-			query=$*
+			[ -n "$ep_choice_to_start" ] && select_first='1'
+			query="$*"
 		fi
-		search_results=$(search_anime "$query")
-		[ -z "$search_results" ] && die "No search results found"
+		search_results="$(search_anime "$query")"
+		[ -z "$search_results" ] && die 'No search results found'
 		anime_selection "$search_results"
-        while [ "$REPLY" = "a" ]; do
+        while [ "$REPLY" = 'a' ]; do
             search_another_anime
         done
-        [ "$REPLY" = "q" ] && exit 0
+        [ "$REPLY" = 'q' ] && exit 0
         if [ "$REPLY" -gt 0 ]; then episode_selection
-        else die "invalid choice"
+        else die 'invalid choice'
         fi
 		;;
 	history)
-		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
+		search_results="$(sed -n -E 's/\t[0-9]*//p' "$logfile")"
 		[ -z "$search_results" ] && die "History is empty"
-		search_results=$(search_for_unwatched "$search_results")
+		search_results="$(search_for_unwatched "$search_results")"
 		anime_selection "$search_results"
-		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+		ep_choice_start="$(sed -n -E "s/${selection_id}\t//p" "$logfile")"
 
 
-        while [ "$REPLY" = "a" ]; do
+        while [ "$REPLY" = 'a' ]; do
             search_another_anime
         done
-        [ "$REPLY" = "q" ] && exit 0
+        [ "$REPLY" = 'q' ] && exit 0
 
 		first_ep_number="0"
-		result=$(get_dpage_link "$anime_id" "$first_ep_number")
+		result="$(get_dpage_link "$anime_id" "$first_ep_number")"
 		if [ -n "$result" ]; then
 			true
 		else
@@ -595,7 +595,7 @@ case $scrape in
 		fi
 		;;
 	*)
-		die "Unexpected Scrape type"
+		die 'Unexpected Scrape type'
 esac
 
 	check_input
@@ -611,57 +611,57 @@ if [ -z "$select_first" ]; then
 	if [ "$auto_play" -eq 0 ]; then
 		inf "Currently playing $selection_id episode" "$episode/$last_ep_number"
 	else
-		auto_play=0
+		auto_play="0"
 	fi
 	if [ "$episode" -ne "$last_ep_number" ]; then
-		menu_line_alternate "next episode" "n"
+		menu_line_alternate 'next episode' 'n'
 	fi
 	if [ "$episode" -ne "$first_ep_number" ]; then
-		menu_line_alternate "previous episode" "p"
+		menu_line_alternate 'previous episode' 'p'
 	fi
 	if [ "$last_ep_number" -ne "$first_ep_number" ]; then
-		menu_line_alternate "select episode" "s"
+		menu_line_alternate 'select episode' 's'
 	fi
-	menu_line_alternate "replay current episode" "r"
-	menu_line_alternate "search for another anime" "a"
-	menu_line_alternate "search history" "h"
-	menu_line_strong "exit" "q"
-	prompt "Enter choice"
+	menu_line_alternate 'replay current episode' 'r'
+	menu_line_alternate 'search for another anime' 'a'
+	menu_line_alternate 'search history' 'h'
+	menu_line_strong 'exit' 'q'
+	prompt 'Enter choice'
 	# process user choice
 	choice="$REPLY"
-	case $choice in
+	case "$choice" in
 		n)
-			ep_choice_start=$((episode + 1))
-			ep_choice_end=""
+			ep_choice_start="$((episode + 1))"
+			ep_choice_end=''
 			;;
 		p)
-			ep_choice_start=$((episode - 1))
-			ep_choice_end=""
+			ep_choice_start="$((episode - 1))"
+			ep_choice_end=''
 			;;
 
 		s)	episode_selection
 			;;
 
 		r)
-			ep_choice_start=$((episode))
-			ep_choice_end=""
+			ep_choice_start="$((episode))"
+			ep_choice_end=''
 			;;
 		a)
-            search_another_anime
+            		search_another_anime
 			;;
 		h)
-            search_history
+            		search_history
 			;;
 
 		N)
-			ep_choice_start=$((episode + 1))
+			ep_choice_start="$((episode + 1))"
 			;;
 		q)
 			break;;
 
 		*)
 			tput clear
-			err "invalid choice"
+			err 'invalid choice'
 			continue
 			;;
 	esac
@@ -670,7 +670,7 @@ if [ -z "$select_first" ]; then
 	open_selection
 
 else
-	wait $!
+	wait "$!"
 	exit
 fi
 done
