feat:onefile

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -2,7 +2,7 @@
 
 # License preamble at the end of the file
 # Version number
-VERSION="3.2.3"
+VERSION="3.3.0"
 
 
 #######################
@@ -32,7 +32,7 @@ help_text () {
 	  -D delete history
 	  -U fetch update from github
 	  -V print version number and exit
-	  -r select provider to scrape first [1-7]
+	  -r select provider to scrape first [1-5]
 	  -x print all video links from all providers to stdout (for debugging purpose)
 
 	Episode selection:
@@ -46,43 +46,140 @@ help_text () {
 EOF
 }
 
-version_text () {
-	inf "Version: $VERSION"
+retry () {
+	err "$*"
+	prompt
 }
 
+# display an error message to stderr (in red)
+err () {
+	printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
+}
+
+#display error message and exit
 die () {
 	err "$*"
 	exit 1
 }
 
-# get the newest version of this script from github and replace it
-update () {
-	for i ; do
-		filename="$(printf '%s' "$i" | sed "s_$root_dir/__")"
-		update="$(curl -A "$agent" -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/$filename")" || die "Connection error"
-		update="$(printf '%s\n' "$update" | diff -u "$i" -)"
-		if [ -z "$update" ]; then
-			inf "$filename is up to date :)"
+# display an informational message (first argument in green, second in magenta)
+inf () {
+	printf "\33[2K\r\033[1;35m%s \033[1;35m%s\033[0m\n" "$1" "$2"
+}
+
+progress() {
+	printf "\33[2K\r\033[1;34m%s\033[0m" "$1"
+}
+
+debug () {
+	printf "\n\033[1;32mReferrer :\033[0m %s\n\033[1;32mlinks >>\n\033[0m%s\n" "$1" "$2"
+}
+
+# prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
+prompt () {
+	[ -n "$*" ] && printf "\33[2K\r\033[1;35m%s\n" "$*"
+	printf "\033[1;35m> \033[0m"
+	read -r REPLY REPLY2
+}
+
+selection_menu() {
+	menu_line_parity=0
+	while read -r option line; do
+		if [ "$option" = "q" ]; then
+			printf "\033[1;31m(\033[1;31m%s\033[1;31m) \033[1;31m%s\033[0m\n" "$option" "$line"
 		else
-			if printf '%s\n' "$update" | patch "$i" - ; then
-				inf "$filename has been updated"
+			if [ "$menu_line_parity" -eq 0 ]; then
+				printf "\033[1;33m(\033[1;33m%s\033[1;33m) \033[1;33m%s\033[0m\n" "$option" "$line"
+				menu_line_parity=1
 			else
-				die "Can't update $filename for some reason!"
+				printf "\033[1;36m(\033[1;36m%s\033[1;36m) \033[1;36m%s\033[0m\n" "$option" "$line"
+				menu_line_parity=0
 			fi
+		fi
+	done <<-EOF
+	$*
+	EOF
+	prompt
+}
+
+selection_menu_fzf() {
+	printf "%s\n%s" "$1" "$2" | fzf --height=30% --border -1 --layout=reverse --header-first --header-lines=1 --cycle --with-nth 2.. | cut -f1 -d' '
+}
+
+version_text () {
+	inf "Version: $VERSION"
+}
+
+# get the newest version of this script from github and replace it
+update_script () {
+	update="$(curl -A "$agent" -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
+	update="$(printf '%s\n' "$update" | diff -u "$0" -)"
+	if [ -z "$update" ]; then
+		inf "Script is up to date :)"
+	else
+		if printf '%s\n' "$update" | patch "$0" - ; then
+			inf "Script has been updated"
+		else
+			die "Can't update for some reason!"
+		fi
 	fi
-	done
+	exit 0
 }
 
 # checks if dependencies are present
 dep_ch () {
 	for dep; do
 		if ! command -v "$dep" >/dev/null ; then
-			err "Program \"$dep\" not found. Please install it."
-			die
+			die "Program \"$dep\" not found. Please install it."
 		fi
 	done
 }
 
+download () {
+	case $2 in
+		*manifest*m3u8*)
+			ffmpeg -loglevel error -stats -referer "$1" -i "$2" -c copy "$download_dir/$3.mp4" ;;
+		*m3u8*)
+			progress "Fetching Metadata.."
+			[ -d "$tmpdir" ] || mkdir "$tmpdir"
+			m3u8_data="$(curl -s "$2")"
+			key_uri="$(printf "%s" "$m3u8_data" | sed -nE 's/^#EXT-X-KEY.*URI="([^"]*)"/\1/p')"
+			m3u8_data="$(printf "%s" "$m3u8_data" | sed "/#/d")"
+			printf "%s" "$m3u8_data" | grep -q "http" || relative_url=$(printf "%s" "$2" | sed "s|[^/]*$||")
+			range=$(printf "%s\n" "$m3u8_data" | wc -l)
+			# Getting and 'decrypting' encryption key
+			if [ -n "$key_uri" ];then
+				key=$(curl -s "$key_uri" | od -A n -t x1 | tr -d ' |\n')
+				iv=$(openssl rand -hex 16)
+			fi
+			# Asyncronously downloading pieces to temporary directory
+			inf "pieces : $range"
+			for i in $(seq "$range"); do
+				curl -s "${relative_url}$(printf "%s" "$m3u8_data" | sed -n "${i}p")" > "$tmpdir/$(printf "%04d" "$i").ts" && printf "\033[2K\r \033[1;32m✓ %s / %s done" "$i" "$range" &
+				jobs -p > "$jobfile"
+				while [ "$(wc -w "$jobfile" | cut -d' ' -f1)" -ge 35 ];do jobs > "$jobfile";sleep 0.05;done
+			done
+			wait
+			# Decrypting and concatenating the pieces
+			if [ -n "$key_uri" ];then
+				progress "Decrypting and Concatenating pieces into single file.."
+				for i in "$tmpdir"/* ; do
+					openssl enc -aes128 -d -K "$key" -iv "$iv" -nopad >> video.ts < "$i"
+				done
+			else
+				progress "Concatenating pieces into single file.."
+				cat "$tmpdir"/* >> video.ts
+			fi
+			# cleanup and encoding
+			rm -rdf "$tmpdir" "$jobfile"
+			inf "Encoding file to mp4 video.."
+			ffmpeg -loglevel error -stats -i "video.ts" -c copy "$download_dir/$3.mp4"
+			rm -f video.ts
+			;;
+		*)	
+			axel -a -k -n 30 --header=Referer:"$1" "$2" -o "$download_dir/$3.mp4" ;;
+	esac
+}
 
 #############
 # SEARCHING #
@@ -102,21 +199,6 @@ episode_list () {
 	select_ep_result=$(printf "%s" "$data" | head -1 | tr "," "\n" | sed '/extra/d' | sed -nE 's_".*":"(.*)".*_\1_p')
 	first_ep_number=1
 	[ -z "$select_ep_result" ] && last_ep_number=0 || last_ep_number=$(printf "%s\n" "$select_ep_result" | wc -l)
-}
-
-#from allanime server
-al_episode_list() {
-	ext_id=$(printf "%s" "$data" | tail -1)
-	al_server_link=$(curl -s -H "x-requested-with:XMLHttpRequest" -X POST "https://animixplay.to/api/search" -d "recomended=$ext_id" -A "$agent" |
-		sed -nE 's_.*"AL","items":\[(.*)\]\},.*_\1_p' | tr '{|}' '\n' | sed -nE 's_"url":"(.*)",.*title.*_\1_p')
-	[ -z "$al_server_link" ] && return 0
-	progress "(Allanime) Searching Episodes.."
-	if printf "%s" "$selection_id" | grep -q "dub"; then
-		al_server_link=$(printf "%s" "$al_server_link" | grep "dub" | head -1)
-	else
-		al_server_link=$(printf "%s" "$al_server_link" | sed 's/-dub//' | head -1)
-	fi
-	al_data=$(curl -s "${base_url}${al_server_link}" -A "$agent" | sed -nE 's_.*epslistplace.*>(.*)</div>_\1_p')
 }
 
 process_hist_entry () {
@@ -167,32 +249,6 @@ generate_link() {
 			result_links="$(curl -A "$agent" -s "https://dood.pm${dood_md5}" -e "$refr" || true)doodstream?token=$(printf "%s" "$dood_md5" | cut -d'/' -f4 || true)&expiry=$(date +%s)000"
 			;;
 		3)
-			provider_name='Streamlare'
-			progress "Fetching $provider_name link.."
-			lare_id=$(printf "%s" "$al_links" | sed -nE 's_.*streamlare.*/e/(.*)_\1_p')
-			[ -z "$lare_id" ] && lare_id=$(printf "%s" "$dpage_url" | sed -nE 's_.*streamlare.*/e/(.*)_\1_p')
-			refr="https://streamlare.com/e/$lare_id"
-			[ -z "$lare_id" ] && return 0
-			lare_token=$(curl -s -A "$agent" "$refr" -L | sed -nE 's/.*csrf-token.*content="(.*)">/\1/p')
-			[ -z "$lare_token" ] || result_links="$(curl -s -A "$agent" -H "x-requested-with:XMLHttpRequest" -X POST "https://streamlare.com/api/video/download/get" -d "{\"id\":\"$lare_id\"}" \
-				-H "x-csrf-token:$lare_token" -H "content-type:application/json;charset=UTF-8" | sed 's/\\//g' | sed -nE 's/.*url":"([^"]*)".*/\1/p')"
-			;;
-		4)
-			provider_name='Okru'
-			progress "Fetching $provider_name links.."
-			ok_id=$(printf "%s" "$al_links" | sed -nE 's_.*ok.*videoembed/(.*)_\1_p')
-			[ -z "$ok_id" ] && ok_id=$(printf "%s" "$dpage_url" | sed -nE 's_.*ok.*videoembed/(.*)_\1_p')
-			refr="https://odnoklassniki.ru/videoembed/$ok_id"
-			[ -z "$ok_id" ] && return 0
-			result_links="$(curl -s "$refr" | sed -nE 's_.*data-options="([^"]*)".*_\1_p' | sed -e 's/&quot;/"/g' -e 's/\u0026/\&/g' -e 's/amp;//g' | sed 's/\\//g' | sed -nE 's/.*videos":(.*),"metadataE.*/\1/p' | tr '{|}' '\n' |
-				sed -nE 's/"name":"mobile","url":"(.*)",.*/144p >\1/p ;
-						s/"name":"lowest","url":"(.*)",.*/240p >\1/p ;
-						s/"name":"low","url":"(.*)",.*/360p >\1/p ;
-						s/"name":"sd","url":"(.*)",.*/480p >\1/p ;
-						s/"name":"hd","url":"(.*)",.*/720p >\1/p ;
-						s/"name":"full","url":"(.*)",.*/1080p >\1/p')"
-			;;
-		5)
 			provider_name='Xstreamcdn'
 			progress "Fetching $provider_name links.."
 			fb_id=$(printf "%s" "$resp" | sed -n "s_.*fembed.*/v/__p")
@@ -201,7 +257,7 @@ generate_link() {
 			result_links="$(curl -A "$agent" -s -X POST "https://fembed-hd.com/api/source/$fb_id" -H "x-requested-with:XMLHttpRequest" |
 				sed -e 's/\\//g' -e 's/.*data"://' | tr "}" "\n" | sed -nE 's/.*file":"(.*)","label":"(.*)","type.*/\2>\1/p')"
 			;;
-		6)
+		4)
 			provider_name='Animixplay'
 			progress "Fetching $provider_name Direct link.."
 			refr="$base_url"
@@ -231,8 +287,6 @@ generate_link() {
 get_video_link() {
 	dpage_url="$1"
 	id=$(printf "%s" "$dpage_url" | sed -nE 's/.*id=(.*)&title.*/\1/p')
-	al_links=$(printf "%s" "$al_data" | sed -e 's_:\[_\n_g' -e 's_:"_\n"_g' | sed -e 's/].*//g' -e '1,2d' | sed -n "${episode}p" | tr -d '"' | tr "," "\n")
-	[ -z "$id" ] && id=$(printf "%s" "$al_links" | sed -nE 's/.*id=(.*)&title.*/\1/p')
 	#multiple sed are used (regex seperated by ';') for extracting only required data from response of embed url
 	resp="$(curl -A "$agent" -s "https://goload.pro/streaming.php?id=$id" |
 		sed -nE 's/.*class="container-(.*)">/\1/p ;
@@ -240,16 +294,16 @@ get_video_link() {
 			s/.*class=".*videocontent-(.*)">/\1/p ;
 			s/.*data-value="(.*)">.*/\1/p ;
 			s/.*data-status="1".*data-video="(.*)">.*/\1/p')"
-	# providers: Doodstream for default, mp4upload for downloading. For best quality use okru, for fallback use goload. Then it's a round robin of which links are returned.
+	# providers: Doodstream for default, mp4upload for downloading. For best quality use animixplay, for fallback use goload. Then it's a round robin of which links are returned.
 	provider=2
 	uname -a | grep -qE '[Aa]ndroid' && provider=3
-	[ "$is_download" -eq 1 ] && provider=1
+	[ "$player_fn" = "download" ] && provider=1
 	[ "$quality" != "best" ] && provider=4
 	[ -n "$select_provider" ] && provider="$select_provider"
 	i=0
-	while [ "$i" -lt 7 ] && [ -z "$result_links" ];do
+	while [ "$i" -lt 5 ] && [ -z "$result_links" ];do
 		generate_link "$provider"
-		provider=$((provider % 7 + 1))
+		provider=$((provider % 5 + 1))
 		if [ "$debug" -eq 1 ]; then
 			debug "$refr" "$result_links"
 			unset result_links
@@ -365,7 +419,6 @@ anime_selection () {
 	selection_id="$(printf "%s" "$search_results" | sed -n "${choice}p" | cut -d':' -f1 | tr -d ' ')"
 	progress "(Gogoanime) Searching Episodes.."
 	episode_list "$selection_id"
-	al_episode_list
 }
 
 # gets episode number from user, makes sure it's in range, skips input if only one episode exists
@@ -376,7 +429,7 @@ episode_selection () {
 		if [ -z "$ep_choice_to_start" ]; then
 			# if branches, because order matters this time
 			while : ; do
-        last_ep_number=$(printf '%s' "$last_ep_number"|tr -d "[:space:]")
+				last_ep_number=$(printf '%s' "$last_ep_number"|tr -d "[:space:]")
 				prompt "To specify a range, use: start_number end_number (Episodes: $first_ep_number-$last_ep_number)"
 				ep_choice_start="$REPLY"
 				ep_choice_end="$REPLY2"
@@ -404,11 +457,7 @@ episode_selection () {
 		# In case the anime contains only a single episode
 		ep_choice_start=1
 	fi
-	if [ -z "$ep_choice_end" ]; then
-		auto_play=0
-	else
-		auto_play=1
-	fi
+	[ -n "$ep_choice_end" ] && auto_play=1
 }
 
 # creates $episodes from $ep_choice_start and $ep_choice_end
@@ -421,10 +470,6 @@ generate_ep_list() {
 ##################
 # VIDEO PLAYBACK #
 ##################
-
-append_history () { # todo: unite this with the temporary histfile writing
-	grep -q "$selection_id" "$logfile" || printf "%s\t%s\n" "$selection_id" $((episode+1)) >> "$logfile"
-}
 
 # opens selected episodes one-by-one
 open_selection() {
@@ -448,16 +493,17 @@ open_episode () {
 	fi
 	[ "$debug" -eq 1 ] && exit 0
 	# write anime and episode number and save to temporary history
+	grep -q "$selection_id" "$logfile" || printf "%s\t%s\n" "$selection_id" $((episode+1)) >> "$logfile"
 	sed -E "s/^${selection_id}\t[0-9]*/${selection_id}\t$((episode+1))/" "$logfile" > "${logfile}.new"
 	[ ! "$PID" = "0" ] && kill "$PID" >/dev/null 2>&1
 	[ -z "$video_url" ] && die "Video URL not found"
 	trackma_title="$(printf '%s' "$anime_id Episode $episode" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++){ $i=toupper(substr($i,1,1)) substr($i,2) }}1')"
 	if [ "$auto_play" -eq 0 ]; then
-		play_episode "$video_url" "$refr" "$trackma_title" "$auto_play"
+		play_episode "$video_url" "$refr" "$trackma_title"
 	else
 		printf "\n"
-		play_episode "$video_url" "$refr" "$trackma_title" "$auto_play"
-		wait "$!"
+		play_episode "$video_url" "$refr" "$trackma_title"
+		wait
 		sleep 2
 	fi
 	PID=$!
@@ -465,6 +511,41 @@ open_episode () {
 	mv "${logfile}.new" "$logfile"
 }
 
+play_episode () {
+	video_url="$1"; refr="$2" trackma_title="$3"
+	if [ "$player_fn" = "download" ];then
+		inf "Currently downloading $trackma_title ($provider_name)"
+	else
+		inf "Currently playing $trackma_title ($provider_name)"
+	fi
+	case "$player_fn" in
+		download)
+			if download "$refr" "$video_url" "$trackma_title"; then
+				inf "Downloaded episode: $trackma_title"
+			else
+				err "Download failed episode: $trackma_title , please retry or check your internet connection"
+			fi
+			;;
+		iina)
+			nohup "$player_fn" "$video_url" --no-stdin --keep-running --mpv-referrer="$refr" --mpv-force-media-title="$trackma_title" > /dev/null 2>&1 & ;;
+		vlc)
+			if uname -a | grep -qE '[Aa]ndroid';then
+				am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "$trackma_title" > /dev/null 2>&1 &
+			else
+				nohup "$player_fn" "$video_url"  --http-referrer="$refr" --meta-title "$trackma_title" --play-and-exit > /dev/null 2&>1 &
+			fi
+			;;
+		"syncplay"|"/Applications/Syncplay.app/Contents/MacOS/syncplay"|"/c/Program Files (x86)/Syncplay/Syncplay.exe")
+			nohup "$player_fn" "$video_url" -- --referrer="$refr" --force-media-title="$trackma_title" & ;;
+		*)
+			if uname -a | grep -qE '[Aa]ndroid';then
+				am start --user 0 -a android.intent.action.VIEW -d "$video_url" -n is.xyz.mpv/.MPVActivity > /dev/null 2>&1 &
+			else
+				nohup "$player_fn" "$video_url" --referrer="$refr" --force-media-title="$trackma_title" > /dev/null 2>&1 &
+			fi
+			;;
+	esac
+}
 
 ############
 # START UP #
@@ -475,7 +556,6 @@ trap 'printf "\033[0m";rm -rdf "video.ts" "$tmpdir" "$jobfile" "$logfile".new;ex
 
 # default options
 agent="Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/100.0"
-is_download=0
 PID=0
 quality=best
 provider_name=""
@@ -485,49 +565,48 @@ choice=
 fzf=0
 auto_play=0
 download_dir="$(pwd)"
-bin_dir="$(dirname "$0")"
-root_dir="$(cd "$bin_dir/.." && pwd)"
-lib_dir="$root_dir/lib/ani-cli"
 case "$(uname)" in
-	Darwin*) . "$lib_dir/player_iina" || die "No iina player script found";; #MacOS specific
-	*) . "$lib_dir/player_mpv" || die "No mpv player script found";;
+	Darwin*) player_fn='iina';;
+	*) player_fn='mpv';;
 esac
 # history file path
-logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
 logdir="${XDG_CACHE_HOME:-$HOME/.cache}"
+logfile="$logdir/ani-hsts"
+jobfile="$logdir/ani-jobs"
+tmpdir="$logdir/ani-temp"
 # create history file and history dir if none found
 [ -d "$logdir" ] || mkdir "$logdir"
 [ -f "$logfile" ] || : > "$logfile"
-# source the UI
-. "$lib_dir/UI" || die "No UI file"
 
 while getopts 'svq:dp:chDUVa:xr:fn' OPT; do
 	case $OPT in
-		d) . "$lib_dir/player_download" || die "No download player script found" ;;
+		d) player_fn='download' ;;
 		a) ep_choice_to_start=$OPTARG ;;
+		U) update_script ;;
 		D)
 			: > "$logfile"
 			exit 0
 			;;
 		p)
-			. "$lib_dir/player_download" || die "No download player script found"
+			player_fn='download'
 			download_dir="$OPTARG"
 			;;
 		n) scrape=New ;;
-		s) . "$lib_dir/player_syncplay" || die "No syncplay player script found";;
+		s)
+			case "$(uname -s)" in
+				Darwin*) player_fn="/Applications/Syncplay.app/Contents/MacOS/syncplay" ;;
+				MINGW*|*Msys) player_fn="/c/Program Files (x86)/Syncplay/Syncplay.exe" ;;
+				*) player_fn="syncplay" ;;
+			esac
+			;;
 		q) quality=$OPTARG ;;
 		x) debug=1 ;;
 		r) select_provider=$OPTARG ;;
     f) fzf=1 ;;
 		c) scrape=History ;;
-		v) . "$lib_dir/player_vlc" || die "No vlc player script found";;
-		U)
-			update "$bin_dir/ani-cli" "$lib_dir/UI" "$lib_dir"/player_*
-			exit 0
-			;;
+		v) player_fn='vlc';;
 		V)
 			version_text
-			ui_version_text
 			exit 0
 			;;
 		*)
@@ -539,7 +618,13 @@ done
 shift $((OPTIND - 1))
 progress "Checking dependencies.."
 # shellcheck disable=SC2046
-dep_ch "curl" "sed" "grep" "openssl" $(player_commands) || true
+dep_ch "curl" "sed" "grep" "openssl" || true
+
+if [ "$player_fn" = "download" ];then
+    dep_ch "ffmpeg" "axel"
+else
+    dep_ch "$player_fn"
+fi
 
 base_url="https://animixplay.to"
 if [ "$scrape" = "Query" ];then
@@ -569,7 +654,6 @@ else
 fi
 
 generate_ep_list
-append_history
 open_selection
 
 ########
@@ -617,7 +701,6 @@ while : ; do
 			;;
 	esac
 	generate_ep_list
-	append_history
 	open_selection
 done
 
