dep_ch change again

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -84,14 +84,21 @@ update_script() {
 
 # checks if dependencies are present
 dep_ch() {
-	for dep; do
-        if ! ( command -v "$dep" >/dev/null ) && ! [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
-            die "Program \"$dep\" not found. Please install it."
-        fi
-        if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
-            die "Program \"$dep\" not found. Please install it."
-        fi
-      done
+for dep; do
+    if ! command -v "$dep" >/dev/null; then
+        [ "$player_function" = "flatpak_mpv" ] && flatpak info io.mpv.Mpv >/dev/null 2>&1 && continue
+        die "Program \"$dep\" not found. Please install it."
+    fi
+done 
+
+#	for dep; do
+#        if ! ( command -v "$dep" >/dev/null ) && ! [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
+#            die "Program \"$dep\" not found. Please install it."
+#        fi
+#        if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
+#            die "Program \"$dep\" not found. Please install it."
+#        fi
+#      done
 }
 
 # SCRAPING
