Converted `[] &&` and `[] ||` to `if` statements.

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,6 +1,22 @@
 #!/bin/sh
 
-# version number
+# ani-cli
+#
+# This program is free software: you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation, either version 3 of the License, or
+# (at your option) any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program.  If not, see <http://www.gnu.org/licenses/>.
+# 
+# Project repository: https://github.com/pystardust/ani-cli 
+# Version number:
 VERSION='1.6.5'
 
 
@@ -60,6 +76,7 @@ update_script () {
 		if echo "$update" | patch "$0" - ; then
 			inf 'Script has been updated'
 		else
+			# due to apostrophe can't convert to '
 			die "Can't update for some reason!"
 		fi
 	fi
@@ -88,7 +105,7 @@ search_anime () {
 	# get anime name along with its id for search term
 	search=$(printf '%s' "$1" | tr ' ' '-' )
 	curl -s "$base_url//search.html" -G -d "keyword=$search" |
-	sed -n -E '
+		sed -n -E '
 		s_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p
 		'
 }
@@ -97,7 +114,7 @@ search_eps () {
 	# get available episodes for anime_id
 	anime_id=$1
 	curl -s "$base_url/category/$anime_id" |
-	sed -n -E '
+		sed -n -E '
 		/^[[:space:]]*<a href="#" class="active" ep_start/{
 		s/.* '\''([0-9]*)'\'' ep_end = '\''([0-9]*)'\''.*/\2/p
 		q
@@ -112,8 +129,7 @@ search_for_unwatched () {
 	while read -r anime_id; do
 		current_ep_number="$(search_eps "$anime_id")"
 		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
-		if [ "$current_ep_number" -ge "$history_ep_number" ]
-		then
+		if [ "$current_ep_number" -ge "$history_ep_number" ]; then
 			unwatched_anime='1'
 			echo "$anime_id"
 		fi
@@ -130,18 +146,23 @@ search_another_anime () {
 	prompt 'Search Anime'
 	query="$REPLY $REPLY2"
 	search_results="$(search_anime "$query")"
-	[ -z "$search_results" ] && die 'No search results found'
+	if [ -z "$search_results" ]; then
+		die 'No search results found'
+	fi
 	anime_selection "$search_results"
 	episode_selection
 }
 
 search_history () {
 	search_results="$(sed -n -E 's/\t[0-9]*//p' "$logfile")"
-	[ -z "$search_results" ] && die 'History is empty'
+	if [ -z "$search_results" ]; then
+		die 'History is empty'
+	fi
 	search_results="$(search_for_unwatched "$search_results")"
 	anime_selection "$search_results"
 	ep_choice_start="$(sed -n -E "s/${selection_id}\t//p" "$logfile")"
 }
+
 
 ##################
 # URL PROCESSING #
@@ -171,8 +192,8 @@ decrypt_link() {
 	ajax=$(echo "$video_id" | openssl enc -aes256 -K "$secret_key" -iv "$iv" -a)
 	#send the request to the ajax url
 	curl -s -H 'x-requested-with:XMLHttpRequest' "$ajax_url" -d "id=$ajax" -d "time=69420691337800813569" |
-	sed -e 's/\].*/\]/' -e 's/\\//g' |
-	grep -Eo 'https:\/\/[-a-zA-Z0-9@:%._\+~#=][a-zA-Z0-9][-a-zA-Z0-9@:%_\+.~#?&\/\/=]*'
+		sed -e 's/\].*/\]/' -e 's/\\//g' |
+		grep -Eo 'https:\/\/[-a-zA-Z0-9@:%._\+~#=][a-zA-Z0-9][-a-zA-Z0-9@:%_\+.~#?&\/\/=]*'
 }
 
 get_video_quality() {
@@ -263,25 +284,29 @@ anime_selection () {
 	if [ -n "$ep_choice_to_start" ] && [ -n "$select_first" ]; then
 		tput clear
 		choice="1"
-	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
-	menu_line_alternate 'search for another anime' 'a'
-	menu_line_strong 'exit' 'q'
+	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then #what is the intention behind this?
+		menu_line_alternate 'search for another anime' 'a'
+		menu_line_strong 'exit' 'q'
 		prompt 'Enter choice'
 		choice="$REPLY $REPLY2"
 	fi
-		# Check if input is a number
-		[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
-		# Select respective anime_id
-		count="1"
-		while read -r anime_id; do
-			if [ "$count" -eq "$choice" ]; then
-				selection_id="$anime_id"
-				break
-			fi
-			count="$((count+1))"
-		done <<-EOF
-		$search_results
-		EOF
+	# Check if input is a number
+	if [ "$choice" -eq "$choice" ] 2>/dev/null; then
+		true
+	else
+		return 0
+	fi
+	# Select respective anime_id
+	count="1"
+	while read -r anime_id; do
+		if [ "$count" -eq "$choice" ]; then
+			selection_id="$anime_id"
+			break
+		fi
+		count="$((count+1))"
+	done <<-EOF
+	$search_results
+	EOF
 	if [ -z "$selection_id" ]; then
 		die 'Invalid number entered'
 	fi
@@ -295,15 +320,11 @@ episode_selection () {
 	# using get_dpage_link to get confirmation from episode 0 if it exists,else first_ep_number becomes "1"
 	first_ep_number="0"
 	result="$(get_dpage_link "$anime_id" "$first_ep_number")"
-	if [ -n "$result" ]; then
-		true
-	else
+	if [ -z "$result" ]; then
 		first_ep_number="1"
 	fi
 	if [ "$last_ep_number" -gt "$first_ep_number" ]; then
-
 		inf 'Range of episodes can be specified: start_number end_number'
-
 		if [ -z "$ep_choice_to_start" ]; then
 			prompt 'Choose episode' "[$first_ep_number-$last_ep_number]"
 			ep_choice_start="$REPLY"
@@ -312,8 +333,7 @@ episode_selection () {
 			ep_choice_start="$ep_choice_to_start" && unset ep_choice_to_start
 		fi
 		whether_half="$(echo "$ep_choice_start" | cut -c1-1)"
-		if [ "$whether_half" = "h" ]
-		then
+		if [ "$whether_half" = "h" ]; then
 			half_ep="1"
 			ep_choice_start="$(echo "$ep_choice_start" | cut -c2-)"
 		fi
@@ -325,16 +345,24 @@ episode_selection () {
 		auto_play="0"
 	else
 		auto_play="1"
-		[ "$ep_choice_end" = "-1" ] && ep_choice_end="$last_ep_number"
+		if [ "$ep_choice_end" = "-1" ]; then
+			ep_choice_end="$last_ep_number"
+		fi
 	fi
 }
 
 check_input() {
 	# checks if input is number, creates $episodes from $ep_choice_start and $ep_choice_end
-	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die 'Invalid number entered'
+	if [ "$ep_choice_start" -eq "$ep_choice_start" ]; then
+	else 
+		die 'Invalid number entered'
+	fi
 	episodes="$ep_choice_start"
 	if [ -n "$ep_choice_end" ]; then
-		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die 'Invalid number entered'
+		if [ "$ep_choice_start" -eq "$ep_choice_start" ]; then
+		else 
+			die 'Invalid number entered'
+		fi
 		# create list of episodes to download/watch
 		episodes="$(seq "$ep_choice_start" "$ep_choice_end")"
 	fi
@@ -346,8 +374,7 @@ check_input() {
 ##################
 
 append_history () {
-	grep -q -w "${selection_id}" "$logfile" ||
-		printf "%s\t%s\n" "$selection_id" "$((episode+1))" >> "$logfile"
+	grep -q -w "${selection_id}" "$logfile" || printf "%s\t%s\n" "$selection_id" "$((episode+1))" >> "$logfile"
 }
 
 open_selection() {
@@ -365,11 +392,14 @@ open_episode () {
 	# Cool way of clearing screen
 	tput clear
 	# checking if episode is in range
-	while [ "$episode" -gt "$last_ep_number" ] || [ -z "$episode" ]
-	do
-		[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die 'Invalid number entered'
-		if [ "$last_ep_number" -eq 0 ]; then
-			die 'Episodes not released yet!'
+	while [ "$episode" -gt "$last_ep_number" ] || [ -z "$episode" ]; do
+		if [ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null; then
+			true
+		else
+			die "Invalid number entered"
+		fi
+		if [ "$last_ep_number" -eq 0 ] 2>/dev/null; then
+			die "Episodes not released yet!"
 		else
 			err 'Episode out of range'
 		fi
@@ -377,8 +407,7 @@ open_episode () {
 		episode="$REPLY $REPLY2"
 	done
 	#processing half episodes
-	if [ "$half_ep" -eq 1 ]
-	then
+	if [ "$half_ep" -eq 1 ]; then
 		temp_ep="$episode"
 		episode="$episode'-5'"
 	fi
@@ -396,9 +425,7 @@ open_episode () {
 		sed -E "
 			s/^${selection_id}\t[0-9]+/${selection_id}\t$((episode+1))/
 		" "$logfile" > "${logfile}.new"
-
 		kill "$PID" >/dev/null 2>&1
-
 		if [ -z "$video_url" ]; then
 			die 'Video URL not found'
 		fi
@@ -429,15 +456,13 @@ open_episode () {
 		inf "Downloading episode $episode ...\n"
 		# add 0 padding to the episode name
 		episode=$(printf '%03d' "$episode")
-		{
-			#uncomment this below line if you are getting low download speeds, and comment next one after below line
-			#aria2c -x 16 -s 16 --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide &&
-				if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide ;then
-					inf "Downloaded episode: $episode"
-				else
-					err "Download failed episode: $episode , please retry or check your internet connection"
-				fi
-		}
+		#uncomment this below line if you are getting low download speeds, and comment next one after below line
+		#aria2c -x 16 -s 16 --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide &&
+		if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide ;then
+			inf "Downloaded episode: $episode"
+		else
+			err "Download failed episode: $episode , please retry or check your internet connection"
+		fi
 	fi
 }
 
@@ -447,7 +472,7 @@ open_episode () {
 ############
 
 # default options
-player_fn="mpv" #video player needs to be able to play urls
+player_fn='mpv' #video player needs to be able to play urls
 is_download="0"
 half_ep="0"
 quality='best'
@@ -463,7 +488,9 @@ logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
 # to clear the colors when exited using SIGINT
 trap 'printf "\033[0m"; exit 1' INT HUP
 # create history file if none found
-[ -f "$logfile" ] || : > "$logfile"
+if [ ! -f "$logfile" ]; then
+	touch "$logfile"
+fi
 
 while getopts 'viq:dp:chDUVa:' OPT; do
 	case $OPT in
@@ -525,34 +552,39 @@ case "$scrape" in
 			prompt 'Search Anime'
 			query="$REPLY $REPLY2"
 		else
-			[ -n "$ep_choice_to_start" ] && select_first='1'
+			if [ -n "$ep_choice_to_start" ]; then
+				select_first='1'
+			fi
 			query="$*"
 		fi
 		search_results="$(search_anime "$query")"
-		[ -z "$search_results" ] && die 'No search results found'
+		if [ -z "$search_results" ]; then
+			die 'No search results found'
+		fi
 		anime_selection "$search_results"
-	while [ "$REPLY" = 'a' ]; do
-		search_another_anime
-	done
-	[ "$REPLY" = 'q' ] && exit 0
-	if [ "$REPLY" -gt 0 ]; then episode_selection
-	else die 'invalid choice'
-	fi
+		while [ "$REPLY" = 'a' ]; do
+			search_another_anime
+		done
+		if [ "$REPLY" = 'q' ]; then
+			exit 0
+		fi
+		if [ "$REPLY" -gt 0 ]; then 
+			episode_selection
+		else 
+			die 'invalid choice'
+		fi
 		;;
 	history)
 		search_history
-
-
-	while [ "$REPLY" = 'a' ]; do
-		search_another_anime
-	done
-	[ "$REPLY" = 'q' ] && exit 0
-
+		while [ "$REPLY" = 'a' ]; do
+			search_another_anime
+		done
+		if [ "$REPLY" = 'q' ]; then
+			exit 0
+		fi
 		first_ep_number="0"
 		result="$(get_dpage_link "$anime_id" "$first_ep_number")"
-		if [ -n "$result" ]; then
-			true
-		else
+		if [ -z "$result" ]; then
 			first_ep_number="1"
 		fi
 		;;
@@ -598,7 +630,7 @@ if [ -z "$select_first" ]; then
 			ep_choice_end=''
 			;;
 		b)
-			prompt "Select quality"
+			prompt ' Select quality'
 			quality="$REPLY"
 			;;
 		p)
