dep_ch rewrite and small improvements

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -85,22 +85,24 @@ update_script() {
 # checks if dependencies are present
 dep_ch() {
 	for dep; do
-        if ! command -v "$dep" >/dev/null; then
-            if [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
-                if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
-                    die "Program \"$dep\" not found. Please install it."
-                fi
-            else
-                die "Program \"$dep\" not found. Please install it."
-            fi
+        if ! ( command -v "$dep" >/dev/null ) && ! [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
+            die "Program \"$dep\" not found. Please install it."
         fi
-	done
+        if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
+            die "Program \"$dep\" not found. Please install it."
+        fi
+
+
+#            if [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
+#                if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
+#                    die "Program \"$dep\" not found. Please install it."
+#                fi
+#            else
+#                die "Program \"$dep\" not found. Please install it."
+#            fi
+        
+    done
 }
-
-#if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
-#			    die "Program \"$dep\" not found. Please install it."
-#fi
-
 
 
 # SCRAPING
@@ -265,7 +267,7 @@ printf "\33[2K\r\033[1;34mChecking dependencies...\033[0m\n"
 dep_ch "wget" "sed" "grep" || true
 if [ "$player_function" = "download" ]; then
 	dep_ch "ffmpeg" "aria2c"
-elif ( uname -a | grep -q 'steamdeck' ) || [ "$player_function" = "flatpak_mpv" ] ;then
+elif [ "$player_function" = "flatpak_mpv" ] ;then
     [ "$player_function" != "debug" ] && [ "$player_function" != "download" ] && dep_ch "flatpak" && dep_ch "flatpak run io.mpv.Mpv"
 elif ! (uname -a | grep -qE '[Aa]ndroid'); then
 	[ "$player_function" != "debug" ] && [ "$player_function" != "download" ] && dep_ch "$player_function"
