feat: vlc player support for all OS
+ chore: indentations
+ fix: arguments resemble v3 behavior
+ fix: dependency checking

Co-authored-by: port19 <port19@port19.xyz>
Co-authored-by: Derisis13 <email.felhasznalasra@gmail.com>
Co-authored-by: CoolnsX <ansari.tan20@gmail.com>
Co-authored-by: chokerman <44473782+justchokingaround@users.noreply.github.com>
Co-authored-by: zenith71 <71zenith@protonmail.com>

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -43,15 +43,15 @@ help_info() {
         Use Syncplay to watch with friends
       -q, --quality
         Specify the video quality
-      --vlc
+      -v, --vlc
         Use VLC to play the video
-      -v, -V, --version
+      -V, --version
         Show the version of the script
       -h, --help
         Show this help message and exit
       -e, --episode
         Specify the number of episodes to watch
-      -u, -U, --update
+      -U, --update
         Update the script
     Some example usages:
       %s -q 720p banana fish
@@ -66,7 +66,7 @@ version_info() {
 }
 
 update_script() {
-	update="$(curl -A "$agent" -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
+	update="$(wget -q -O - -U "$agent" "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
 	update="$(printf '%s\n' "$update" | diff -u "$0" -)"
 	if [ -z "$update" ]; then
 		printf "Script is up to date :)\n"
@@ -83,10 +83,7 @@ update_script() {
 # checks if dependencies are present
 dep_ch() {
 	for dep; do
-		if ! command -v "$dep" >/dev/null; then
-			[ "$player_function" = "flatpak_mpv" ] && ! flatpak info io.mpv.Mpv 2>&1 | grep -q 'error' && continue
-			die "Program \"$dep\" not found. Please install it."
-		fi
+		command -v "$dep" >/dev/null || die "Program \"$dep\" not found. Please install it."
 	done
 }
 
@@ -190,16 +187,16 @@ download() {
 play_episode() {
 	get_episode_url
 	case "$player_function" in
-	    debug) printf "All links:\n%s\nSelected link:\n%s\n" "$links" "$episode" ;;
-	    mpv|mpv.exe) nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    mpv_android) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
-	    vlc_android) nohup  am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
-	    iina) nohup "$player_function" --no-stdin --keep-running --mpv-force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    flatpak_mpv) flatpak run io.mpv.Mpv --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    vlc) nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    *yncpla*) nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
-	    download) "$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}" ;;
-	    *) nohup "$player_function" >/dev/null 2>&1 & ;;
+		debug) printf "All links:\n%s\nSelected link:\n%s\n" "$links" "$episode" ;;
+		mpv*) nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+		android_mpv) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
+		android_vlc) nohup  am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
+		iina) nohup "$player_function" --no-stdin --keep-running --mpv-force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+		flatpak_mpv) flatpak run io.mpv.Mpv --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+		vlc*) nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+		*yncpla*) nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
+		download) "$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}" ;;
+		*) nohup "$player_function" >/dev/null 2>&1 & ;;
 	esac
 	[ "$use_external_menu" = "1" ] && wait
 }
@@ -213,11 +210,11 @@ media_locale="${ANI_CLI_MEDIA_LOCALE:-en-US}"
 download_dir="${ANI_CLI_DOWNLOAD_DIR:-.}"
 quality="${ANI_CLI_QUALITY:-best}"
 case "$(uname -a)" in
-*Darwin*) player_function="${ANI_CLI_PLAYER:-iina}" ;; # mac OS
-*ndroid*) player_function="${ANI_CLI_PLAYER:-mpv_android}" ;; # Android OS
-*steamdeck*) player_function="${ANI_CLI_PLAYER:-flatpak_mpv}" ;; # steamdeck OS
-*MINGW*) player_function="${ANI_CLI_PLAYER:-mpv.exe}" ;; # Windows OS
-*) player_function="${ANI_CLI_PLAYER:-mpv}" ;; # Linux OS
+	*Darwin*) player_function="${ANI_CLI_PLAYER:-iina}" ;; # mac OS
+	*ndroid*) player_function="${ANI_CLI_PLAYER:-android_mpv}" ;; # Android OS (termux)
+	*steamdeck*) player_function="${ANI_CLI_PLAYER:-flatpak_mpv}" ;; # steamdeck OS
+	*MINGW*) player_function="${ANI_CLI_PLAYER:-mpv.exe}" ;; # Windows OS
+	*) player_function="${ANI_CLI_PLAYER:-mpv}" ;; # Linux OS
 esac
 
 use_external_menu="${ANI_CLI_EXTERNAL_MENU:-0}"
@@ -229,7 +226,14 @@ search="${ANI_CLI_DEFAULT_SOURCE:-scrape}"
 
 while [ $# -gt 0 ]; do
 	case "$1" in
-	--vlc) player_function=vlc && shift ;;
+	-v | --vlc) 
+		case "$(uname -a)" in
+			*ndroid*) player_function="android_vlc" ;;
+			MINGW*)	player_function="vlc.exe" ;;
+			*)	player_function="vlc" ;;
+		esac
+		shift
+		;;
 	-s | --syncplay)
 		case "$(uname -s)" in
 		Darwin*) player_function="/Applications/Syncplay.app/Contents/MacOS/syncplay" ;;
@@ -241,20 +245,25 @@ while [ $# -gt 0 ]; do
 	-q | --quality) quality="$2" && shift 2 ;;
 	-c | --continue) search=history && shift ;;
 	-d | --download) player_function=download && shift ;;
-	-v | -V | --version) version_info ;;
+	-V | --version) version_info ;;
 	-h | --help) help_info && exit 0 ;;
 	-e | --episode) ep_no="$2" && shift 2 ;;
-	-u | -U | --update) update_script ;;
+	-U | --update) update_script ;;
 	*) query="$(printf "%s" "$query $1" | sed "s/^ //;s/ /%20/g")" && shift ;;
 	esac
 done
 printf "\33[2K\r\033[1;34mChecking dependencies...\033[0m\n"
 dep_ch "wget" "sed" "grep" || true
-if [ "$player_function" = "download" ]; then
-	dep_ch "ffmpeg" "aria2c"
-elif ! (uname -a | grep -qE '[Aa]ndroid'); then
-	[ "$player_function" != "debug" ] && [ "$player_function" != "download" ] && dep_ch "$player_function"
-fi
+case "$player_function" in
+	debug) ;;
+	download) dep_ch "ffmpeg" "aria2c" ;;
+	flatpak*) 
+		dep_ch "flatpak"
+		flatpak info io.mpv.Mpv >/dev/null 2>&1 || die "Program \"mpv (flatpak)\" not found. Please install it."
+		;;
+	android*) printf "Dependency checking of players on Android is disabled\n" ;;
+	*) dep_ch "$player_function" ;;
+esac
 
 # searching
 case "$search" in
