feat: add -R/--random flag for anime discovery mode (#1601)

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-version_number="4.10.4"
+version_number="4.11.0"
 
 # UI
 
@@ -82,6 +82,8 @@ help_info() {
         Use given title as ani-skip query
       -N, --nextep-countdown
         Display a countdown to the next episode
+      -R, --random
+        Browse random anime (discover mode)
       -U, --update
         Update the script
     Some example usages:
@@ -227,6 +229,14 @@ get_episode_url() {
     else
         [ -z "$episode" ] && die "Episode not released!"
     fi
+}
+
+# fetch a random/discovery list of anime (random page of top anime)
+random_anime() {
+    #shellcheck disable=SC2016
+    random_gql='query( $search: SearchInput $limit: Int $page: Int $translationType: VaildTranslationTypeEnumType $countryOrigin: VaildCountryOriginEnumType ) { shows( search: $search limit: $limit page: $page translationType: $translationType countryOrigin: $countryOrigin ) { edges { _id name availableEpisodes __typename } }}'
+    rand_page=$(($(od -An -N2 -tu2 /dev/urandom | tr -d ' ') % 30 + 1))
+    curl -e "$allanime_refr" -s -G "${allanime_api}/api" --data-urlencode "variables={\"search\":{\"allowAdult\":false,\"allowUnknown\":false,\"sortBy\":\"Top\"},\"limit\":26,\"page\":${rand_page},\"translationType\":\"$mode\",\"countryOrigin\":\"JP\"}" --data-urlencode "query=$random_gql" -A "$agent" | sed 's|Show|\n|g' | sed -nE "s|.*_id\":\"([^\"]*).*\"name\":\"(.+)\".*${mode}\":\"?([1-9][^,]*).*|\1\t\2 (\3 episodes)|p" | sed 's/\\"//g'
 }
 
 # search the query and give results
@@ -473,6 +483,7 @@ while [ $# -gt 0 ]; do
             shift
             ;;
         -N | --nextep-countdown) search=nextep ;;
+        -R | --random) search=random ;;
         -U | --update) update_script ;;
         *) query="$(printf "%s" "$query $1" | sed "s|^ ||;s| |+|g")" ;;
     esac
@@ -496,6 +507,20 @@ esac
 
 # searching
 case "$search" in
+    random)
+        printf "\33[2K\r\033[1;35mFetching random anime to discover...\033[0m\n"
+        anime_list=$(random_anime)
+        [ -z "$anime_list" ] && die "Could not fetch anime list!"
+        result=$(printf "%s" "$anime_list" | nl -w 2 | sed 's/^[[:space:]]//')
+        result=$(printf "%s" "$result" | nth "Discover anime: ")
+        [ -z "$result" ] && exit 1
+        title=$(printf "%s" "$result" | cut -f2)
+        allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
+        id=$(printf "%s" "$result" | cut -f1)
+        ep_list=$(episodes_list "$id")
+        [ -z "$ep_no" ] && ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$multi_selection_flag")
+        [ -z "$ep_no" ] && exit 1
+        ;;
     history)
         anime_list=$(while read -r ep_no id title; do process_hist_entry & done <"$histfile")
         wait
