Properly Done (sort of)

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -200,20 +200,26 @@ search_anime() {
 
 time_until_next_ep() {
     animeschedule="https://animeschedule.net"
-
-    schedule_title="$(printf "%s" "$1" | cut -d'(' -f1 | tr -d '[:punct:]' | sed "s| |-|g" | sed 's/.$//' | sed "s|-Season-|-|g")"
-    schedule_query="$(printf "%s" "$schedule_title" | sed "s|-|%20|g")"
-
-    schedule_title="$(printf "%s" "$schedule_title" | awk '{print tolower($0)}' | sed 's/[0-9]//g' | sed 's/.$//')"
-    schedule_query="$(printf "%s" "$schedule_query" | awk '{print tolower($0)}')"
-
-    schedule_query="$(curl -s "$animeschedule/shows?q=$schedule_query" | awk -F '"' '{print $2}' | grep "$schedule_title" | head -n1 | sed "s|/shows/||g")"
-    
+    schedule_title="$(printf "%s" "$1" | awk '{print tolower($0)}')"
+    schedule_query="$(printf "%s" "$schedule_title" | sed 's|%20|-|g')"
     fetched="$(curl -s "$animeschedule/anime/$schedule_query")"
-    ttne="$(printf "%s" "$fetched" | grep 'countdown-time countdown-time-raw' | uniq | awk -F '"' '{print $4}')"
 
-    [ -n "$ttne" ] && echo "Next episode in: " "$ttne"
-    [ -z "$ttne" ] && echo "No information about next episode"
+    
+    if printf "%s" "$fetched" | grep -q "Not Found"; then
+        anime_list="$(curl -s "$animeschedule/shows?q=$schedule_title" | awk -F '"' '{print $2}' | grep "$schedule_query" | uniq | grep -v "/anime/")"
+        for anime in $anime_list; do
+            fetched="$(curl -s "$animeschedule/anime/$anime")"
+            main_title="$(printf "%s" "$fetched" | grep 'anime-header-main-title' | grep -v '{' | awk -F '>' '{print $2}' | awk -F '<' '{print $1}')"
+            english_title="$(printf "%s" "$fetched" | grep 'anime-header-english-title' | grep -v '{' | awk -F '>' '{print $2}' | awk -F '<' '{print $1}')"
+            ttne="$(printf "%s" "$fetched" | grep 'countdown-time countdown-time-raw' | uniq | awk -F '"' '{print $4}')"
+            [ -n "$ttne" ] && printf "%s / %s\n%s\n---\n" "$main_title" "$english_title" " -  Next episode in: $ttne" | more
+            [ -z "$ttne" ] && printf "%s / %s\n%s\n---\n" "$main_title" "$english_title" " -  Finished" | more
+        done
+    else
+        ttne="$(printf "%s" "$fetched" | grep 'countdown-time countdown-time-raw' | uniq | awk -F '"' '{print $4}')"
+        [ -n "$ttne" ] && echo "Next episode in: " "$ttne"
+        [ -z "$ttne" ] && echo "Finished"
+    fi
 
     die
 }
@@ -229,7 +235,6 @@ episodes_list() {
 # PLAYING
 
 process_hist_entry() {
-    [ "$countdown" = "1" ] && ttne="$(time_until_next_ep "$title")"
     [ -n "$ttne" ] && ttne="$(printf " - next episode in: %s" "$ttne")"
     ep_list=$(episodes_list "$id")
     ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null
@@ -347,7 +352,6 @@ use_external_menu="${ANI_CLI_EXTERNAL_MENU:-0}"
 skip_intro="${ANI_CLI_SKIP_INTRO:-0}"
 # shellcheck disable=SC2154
 skip_title="$ANI_CLI_SKIP_TITLE"
-countdown="${ANI_CLI_NEP_COUNTDOWN:-0}"
 [ -t 0 ] || use_external_menu=1
 hist_dir="${ANI_CLI_HIST_DIR:-${XDG_STATE_HOME:-$HOME/.local/state}/ani-cli}"
 [ ! -d "$hist_dir" ] && mkdir -p "$hist_dir"
@@ -408,9 +412,7 @@ while [ $# -gt 0 ]; do
             skip_title="$2"
             shift
             ;;
-        -N | --nextep-countdown)
-            countdown=1
-            ;;
+        -N | --nextep-countdown) search=nextep;;
         -U | --update) update_script ;;
         *) query="$(printf "%s" "$query $1" | sed "s|^ ||;s| |+|g")" ;;
     esac
@@ -449,6 +451,18 @@ case "$search" in
         ep_no=$(printf "%s" "$ep_list" | sed -n "/^${ep_no}$/{n;p;}") 2>/dev/null
         allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
         ;;
+    nextep)
+        if [ "$use_external_menu" = "0" ]; then
+            while [ -z "$query" ]; do
+                printf "\33[2K\r\033[1;36mSearch anime: \033[0m" && read -r query
+            done
+        else
+            [ -z "$query" ] && query=$(printf "" | external_menu "" "Search anime: ")
+            [ -z "$query" ] && exit 1
+        fi
+        query=$(printf "%s" "$query" | sed 's| |%20|g')
+        time_until_next_ep "$query"
+        ;;
     *)
         if [ "$use_external_menu" = "0" ]; then
             while [ -z "$query" ]; do
@@ -468,7 +482,6 @@ case "$search" in
         allanime_title="$(printf "%s" "$title" | cut -d'(' -f1 | tr -d '[:punct:]')"
         id=$(printf "%s" "$result" | cut -f1)
         ep_list=$(episodes_list "$id")
-        [ "$countdown" = "1" ] && time_until_next_ep "$title"
         [ -z "$ep_no" ] && ep_no=$(printf "%s" "$ep_list" | nth "Select episode: " "$multi_selection_flag")
         [ -z "$ep_no" ] && exit 1
         ;;
