Shellcheck compliance, small cleanup

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -68,8 +68,7 @@ die () {
 
 update_script () {
 	# get the newest version of this script from github and replace it
-	update="$(curl -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli" |
-		diff -u "$0" -)"
+	update="$(curl -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli" | diff -u "$0" -)"
 	if [ -z "$update" ]; then
 		inf 'Script is up to date :)'
 	else
@@ -284,7 +283,7 @@ anime_selection () {
 	if [ -n "$ep_choice_to_start" ] && [ -n "$select_first" ]; then
 		tput clear
 		choice="1"
-	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then #what is the intention behind this?
+	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
 		menu_line_alternate 'search for another anime' 'a'
 		menu_line_strong 'exit' 'q'
 		prompt 'Enter choice'
@@ -353,13 +352,15 @@ episode_selection () {
 
 check_input() {
 	# checks if input is number, creates $episodes from $ep_choice_start and $ep_choice_end
-	if [ "$ep_choice_start" -eq "$ep_choice_start" ]; then
+	if [ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null; then
+		true
 	else 
 		die 'Invalid number entered'
 	fi
 	episodes="$ep_choice_start"
 	if [ -n "$ep_choice_end" ]; then
-		if [ "$ep_choice_start" -eq "$ep_choice_start" ]; then
+		if [ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null; then
+			true
 		else 
 			die 'Invalid number entered'
 		fi
@@ -458,7 +459,7 @@ open_episode () {
 		episode=$(printf '%03d' "$episode")
 		#uncomment this below line if you are getting low download speeds, and comment next one after below line
 		#aria2c -x 16 -s 16 --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide &&
-		if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide ;then
+		if aria2c --referer="$dpage_link" "$video_url" --dir="$download_dir" -o "${anime_id}-${episode}.mp4" --download-result=hide; then
 			inf "Downloaded episode: $episode"
 		else
 			err "Download failed episode: $episode , please retry or check your internet connection"
@@ -622,7 +623,6 @@ if [ -z "$select_first" ]; then
 	menu_line_alternate "select quality (current: $quality)" 'b'
 	menu_line_strong 'exit' 'q'
 	prompt 'Enter choice'
-	# process user choice
 	choice="$REPLY"
 	case "$choice" in
 		n)
@@ -630,7 +630,7 @@ if [ -z "$select_first" ]; then
 			ep_choice_end=''
 			;;
 		b)
-			prompt ' Select quality'
+			prompt 'Select quality'
 			quality="$REPLY"
 			;;
 		p)
@@ -659,7 +659,7 @@ if [ -z "$select_first" ]; then
 			;;
 		*)
 			tput clear
-			err 'invalid choice'
+			err 'Invalid choice'
 			continue
 			;;
 	esac
