fix: are nested ifs bad?

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -85,16 +85,13 @@ update_script() {
 # checks if dependencies are present
 dep_ch() {
 	for dep; do
-if ! command -v "$dep" >/dev/null; then
-            if [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
-                if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
-                    die "Program \"$dep\" not found. Please install it."
-                fi
-            else
-                die "Program \"$dep\" not found. Please install it."
-            fi
+        if ! ( command -v "$dep" >/dev/null ) && ! [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
+            die "Program \"$dep\" not found. Please install it."
         fi
-	done
+        if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
+            die "Program \"$dep\" not found. Please install it."
+        fi
+      done
 }
 
 # SCRAPING
