refactor: extracted the UI into a separate file feat: updating UI with main program feat: announcing UI version and theme with program version

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -60,7 +60,8 @@ help_text () {
 }
 
 version_text () {
-	inf "Version: $VERSION" >&2
+	inf "Version: $VERSION"
+	ui_version_text
 }
 
 die () {
@@ -78,9 +79,10 @@ update_script () {
 		if printf '%s\n' "$update" | patch "$0" - ; then
 			inf "Script has been updated"
 		else
-			die "Can't update for some reason!"
+			die "Can't update script for some reason!"
 		fi
 	fi
+	update_ui
 }
 
 # checks if dependencies are present
@@ -258,64 +260,24 @@ get_video_quality_m3u8() {
 			idx="auto" ;;
 	esac
 	if [ "$idx" -lt 1 ] 2>/dev/null || [ "$idx" -gt "$m3u8_links_count" ] 2>/dev/null ;then
-		err "Current video quality is not available (defaulting to best quality)"		 
+		quality_not_available
 		idx="auto"
 	fi
 	[ "$idx" != "auto" ] 2>/dev/null && printf '%s' "$video_url" | grep -qE "gogocdn.*m3u.*" && idx=$((idx-1))
 }
 
 
-###############
-# TEXT OUTPUT #
-###############
-
-# display an error message to stderr (in red)
-err () {
-	printf "\033[1;31m%s\033[0m\n" "$*" >&2
-}
-
-# display an informational message (first argument in green, second in magenta)
-inf () {
-	printf "\033[1;35m%s \033[1;35m%s\033[0m\n" "$1" "$2"
-}
-
-# prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
-prompt () {
-	printf "\033[1;35m%s\033[1;35m%s\033[1;34m\033[0m" "$1" "$2"
-	read -r REPLY REPLY2
-}
-
-# displays an even (cyan) line of a menu line with $2 as an indicator in () and $1 as the option
-menu_line_even () {
-	printf "\033[1;36m(\033[1;36m%s\033[1;36m) \033[1;36m%s\033[0m\n" "$2" "$1"
-}
-
-# displays an odd (yellow) line of a menu line with $2 as an indicator in () and $1 as the option
-menu_line_odd() {
-	printf "\033[1;33m(\033[1;33m%s\033[1;33m) \033[1;33m%s\033[0m\n" "$2" "$1"
-}
-
-# display alternating menu lines (even and odd)
-menu_line_alternate() {
-	menu_line_parity=${menu_line_parity:-0}
-	if [ "$menu_line_parity" -eq 0 ]; then
-		menu_line_odd "$1" "$2"
-		menu_line_parity=1
-	else
-		menu_line_even "$1" "$2"
-		menu_line_parity=0
-	fi
-}
-
-# displays a warning (red) line of a menu line with $2 as an indicator in [] and $1 as the option
-menu_line_strong() {
-	printf "\033[1;31m(\033[1;31m%s\033[1;31m) \033[1;31m%s\033[0m\n" "$2" "$1"
-}
-
-
 #################
 # INPUT PARSING #
 #################
+
+append () {
+	if [ -z "$1" ]; then
+		printf "%s\n%s" "$2" "$3"
+	else
+		printf  "%s\n%s\n%s" "$1" "$2" "$3"
+	fi
+}
 
 # only lets the user pass in case of a valid search
 process_search () {
@@ -327,8 +289,7 @@ process_search () {
 			search_results=$(search_anime "$extended_search_results")
 			break
 		fi
-		err 'No search results found'
-		prompt 'Search Anime: '
+		retry 'No search results found'
 		query="$REPLY $REPLY2"
 		search_results=$(search_anime "$query")
 	done
@@ -339,10 +300,11 @@ process_search () {
 # anime-selection menu handling function
 anime_selection () {
 	count=1
+	unset selection_list
 	while read -r anime_id; do
 	displayed_title="$(printf '%s' "$anime_id" | tr '-' ' ' | awk '{for(i=1;i<=NF-2;i++) printf $i" "; print "("$(NF-1), $NF")"}' \
 		| awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1')"
-		menu_line_alternate "$displayed_title" "$count"
+		selection_list=$(append "$selection_list" "$displayed_title" "$count")
 		: $((count+=1))
 	done <<-EOF
 	$search_results
@@ -351,13 +313,12 @@ anime_selection () {
 		tput clear
 		choice=1
 	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
-		menu_line_strong "exit" "q"
-		prompt "> "
+		selection_list=$(append "$selection_list" "exit" "q")
+		selection_menu "$selection_list"
 		choice="$REPLY"
 		while ! [ "$choice" -eq "$choice" ] 2>/dev/null || [ "$choice" -lt 1 ] || [ "$choice" -ge "$count" ] || [ "$choice" = " " ]; do
 			[ "$choice" = "q" ] && exit 0
-			err "Invalid choice entered"
-			prompt "> "
+			retry "Invalid choice entered"
 			choice="$REPLY"
 		done
 	fi
@@ -380,9 +341,7 @@ episode_selection () {
 		if [ -z "$ep_choice_to_start" ]; then
 			# if branches, because order matters this time
 			while : ; do
-				inf "To specify a range, use: start_number end_number"
-				inf "Episodes:" "($first_ep_number-$last_ep_number)"
-				prompt "> "
+				get_input "To specify a range, use: start_number end_number (Episodes: $first_ep_number-$last_ep_number)" # won't work with \n
 				ep_choice_start="$REPLY"
 				ep_choice_end="$REPLY2"
 				if [ "$REPLY" = q ]; then
@@ -493,11 +452,13 @@ trackma_title="$(printf '%s' "$anime_id" | tr '-' ' ' | awk '{for(i=1;i<=NF;i++)
 			set -- "$player_fn" "$video_url" --vid="$idx" --referrer="$refr" --force-media-title="$trackma_title $episode"
 			;;
 	esac
+	display_name=$(printf '%s' "$selection_id" | sed 's/-episode-//')
 	# Run Command
 	if [ "$auto_play" -eq 0 ]; then
+		inf "Currently playing $display_name episode" "$episode/$last_ep_number"
 		nohup "$@" > /dev/null 2>&1 &
 	else
-		inf "Currently playing$display_name episode" "$episode/$last_ep_number, Range: $ep_choice_start-$ep_choice_end"
+		inf "Currently playing$display_name episode" "$episode/$last_ep_number, Range: $ep_choice_start/$ep_choice_end"
 		"$@" > /dev/null 2>&1
 		sleep 2
 	fi
@@ -530,6 +491,8 @@ logdir="${XDG_CACHE_HOME:-$HOME/.cache}"
 # create history file and history dir if none found
 [ -d "$logdir" ] || mkdir "$logdir"
 [ -f "$logfile" ] || : > "$logfile"
+
+. ./UI || die "No UI file"
 
 while getopts 'svq:dp:chDUVa:' OPT; do
 	case $OPT in
@@ -585,7 +548,7 @@ base_url="https://goload.pro"
 case $scrape in
 	query)
 		if [ -z "$*" ]; then
-			prompt "Search Anime: "
+			get_input "Search Anime:"
 			query="$REPLY $REPLY2"
 		else
 			if [ -n "$ep_choice_to_start" ]; then
@@ -616,19 +579,16 @@ updateurl &
 
 while :; do
 if [ -z "$select_first" ]; then
-	if [ "$auto_play" -eq 0 ]; then
-		display_name=$(printf '%s' "$selection_id" | sed 's/-episode-//')
-		inf "Currently playing $display_name episode" "$episode/$last_ep_number"
-	else
-		auto_play=0
-	fi
-	[ "$episode" -ne "$last_ep_number" ] && menu_line_alternate 'next' 'n'
-	[ "$episode" -ne "$first_ep_number" ] && menu_line_alternate 'previous' 'p'
-	menu_line_alternate "replay" "r"
-	[ "$last_ep_number" -ne "$first_ep_number" ] && menu_line_alternate 'select' 's'
-	menu_line_strong "exit" "q"
-	prompt "> "
-	choice="$REPLY"
+	auto_play=0
+	unset menu
+	unset options
+	[ "$episode" -ne "$last_ep_number" ] && menu=$(append "$menu" 'next' 'n')
+	[ "$episode" -ne "$first_ep_number" ] && menu=$(append "$menu" 'previous' 'p')
+	menu=$(append "$menu" 'replay' 'r')
+	[ "$first_ep_number" -ne "$last_ep_number" ] && menu=$(append "$menu" 'select' 's')
+	menu=$(append "$menu" 'exit' 'q')
+	selection_menu "$menu"
+		choice="$REPLY"
 	case $choice in
 		n)
 			ep_choice_start=$((episode + 1))
