feat: vlc player support for all OS

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -66,7 +66,7 @@ version_info() {
 }
 
 update_script() {
-	update="$(curl -A "$agent" -s "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
+	update="$(wget -q -O - -U "$agent" "https://raw.githubusercontent.com/pystardust/ani-cli/master/ani-cli")" || die "Connection error"
 	update="$(printf '%s\n' "$update" | diff -u "$0" -)"
 	if [ -z "$update" ]; then
 		printf "Script is up to date :)\n"
@@ -191,12 +191,12 @@ play_episode() {
 	get_episode_url
 	case "$player_function" in
 	    debug) printf "All links:\n%s\nSelected link:\n%s\n" "$links" "$episode" ;;
-	    mpv|mpv.exe) nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    mpv_android) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
-	    vlc_android) nohup  am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
+	    mpv*) nohup "$player_function" --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+	    android_mpv) nohup am start --user 0 -a android.intent.action.VIEW -d "$episode" -n is.xyz.mpv/.MPVActivity >/dev/null 2>&1 & ;;
+	    android_vlc) nohup  am start --user 0 -a android.intent.action.VIEW -d "$episode" -n org.videolan.vlc/org.videolan.vlc.gui.video.VideoPlayerActivity -e "title" "${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
 	    iina) nohup "$player_function" --no-stdin --keep-running --mpv-force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
 	    flatpak_mpv) flatpak run io.mpv.Mpv --force-media-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
-	    vlc) nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
+	    vlc*) nohup "$player_function" --video-title="${allanime_title}episode-${ep_no}-${mode}" "$episode" >/dev/null 2>&1 & ;;
 	    *yncpla*) nohup "$player_function" "$episode" -- --force-media-title="${allanime_title}episode-${ep_no}-${mode}" >/dev/null 2>&1 & ;;
 	    download) "$player_function" "$episode" "${allanime_title}episode-${ep_no}-${mode}" ;;
 	    *) nohup "$player_function" >/dev/null 2>&1 & ;;
@@ -214,7 +214,7 @@ download_dir="${ANI_CLI_DOWNLOAD_DIR:-.}"
 quality="${ANI_CLI_QUALITY:-best}"
 case "$(uname -a)" in
 *Darwin*) player_function="${ANI_CLI_PLAYER:-iina}" ;; # mac OS
-*ndroid*) player_function="${ANI_CLI_PLAYER:-mpv_android}" ;; # Android OS
+*ndroid*) player_function="${ANI_CLI_PLAYER:-android_mpv}" ;; # Android OS
 *steamdeck*) player_function="${ANI_CLI_PLAYER:-flatpak_mpv}" ;; # steamdeck OS
 *MINGW*) player_function="${ANI_CLI_PLAYER:-mpv.exe}" ;; # Windows OS
 *) player_function="${ANI_CLI_PLAYER:-mpv}" ;; # Linux OS
@@ -229,7 +229,14 @@ search="${ANI_CLI_DEFAULT_SOURCE:-scrape}"
 
 while [ $# -gt 0 ]; do
 	case "$1" in
-	--vlc) player_function=vlc && shift ;;
+	--vlc) 
+		case "$(uname -a)" in
+			*ndroid*) player_function="android_vlc" ;;
+			MINGW*)	player_function="vlc.exe" ;;
+			*)	player_function="vlc" ;;
+		esac
+		shift
+		;;
 	-s | --syncplay)
 		case "$(uname -s)" in
 		Darwin*) player_function="/Applications/Syncplay.app/Contents/MacOS/syncplay" ;;
