Fix: fixed episode selection

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -336,17 +336,30 @@ episode_selection () {
 		die "Episodes not released yet!"
 	fi
 	if [ "$last_ep_number" -gt "$first_ep_number" ]; then
-		inf "Range of episodes can be specified: start_number end_number"
 		if [ -z "$ep_choice_to_start" ]; then
-			prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
-			ep_choice_start="$REPLY"
-			ep_choice_end="$REPLY2"
-			while [ "$ep_choice_start" -lt "$first_ep_number" ] 2> /dev/null || [ "$ep_choice_end" -gt "$last_ep_number" ] 2> /dev/null ||
-				[ "$ep_choice_start" -gt "$last_ep_number" ] 2> /dev/null || [ -z "$ep_choice_start" ] 2> /dev/null || [ "$ep_choice_end" != -1 ]; do
-					err "Invalid number chosen"
-					prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
-					ep_choice_start="$REPLY"
-					ep_choice_end="$REPLY2"
+			# if branches, because order matters this time
+			while : ; do
+				inf "Range of episodes can be specified: start_number end_number"
+				prompt "Choose episode" "[$first_ep_number-$last_ep_number]"
+				ep_choice_start="$REPLY"
+				ep_choice_end="$REPLY2"
+				if [ "$REPLY" = q ]; then
+					exit 0
+				fi
+				[ "$ep_choice_end" = "-1" ] && ep_choice_end="$last_ep_number"
+				if ! [ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || { [ -n "$ep_choice_end" ] && ! [ "$ep_choice_end"  -eq "$ep_choice_end" ] 2>/dev/null; }; then
+					err "Invalid number(s)"
+					continue
+				fi
+				if [ "$ep_choice_start" -gt "$last_ep_number" ] 2>/dev/null || [ "$ep_choice_end" -gt "$last_ep_number" ] 2>/dev/null || [ "$ep_choice_start" -lt "$first_ep_number" ] 2>/dev/null; then
+					err "Episode out of range"
+					continue
+				fi
+				if [ "$ep_choice_end" -le "$ep_choice_start" ]; then
+					err "Invalid range"
+					continue
+				fi
+				break
 			done
 		else
 			ep_choice_start="$ep_choice_to_start" && unset ep_choice_to_start
@@ -364,7 +377,6 @@ episode_selection () {
 		auto_play=0
 	else
 		auto_play=1
-		[ "$ep_choice_end" = "-1" ] && ep_choice_end="$last_ep_number"
 	fi
 }
 
