refactor:       * add functions to avoid redundancy                 * formatting                 * add removing of temp logfile

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -102,9 +102,7 @@ search_anime () {
 	# get anime name along with its id for search term
 	search=$(printf '%s' "$1" | tr ' ' '-' )
 	curl -s "$base_url//search.html" -G -d "keyword=$search" |
-		sed -n -E '
-		s_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p
-		'
+		sed -n -E 's_^[[:space:]]*<a href="/category/([^"]*)" title="([^"]*)".*_\1_p'
 }
 
 search_eps () {
@@ -141,10 +139,7 @@ search_another_anime () {
 	tput clear
 	prompt "Search Anime"
 	query="$REPLY $REPLY2"
-	search_results=$(search_anime "$query")
-	[ -z "$search_results" ] && die "No search results found"
-	anime_selection "$search_results"
-	episode_selection
+    process_search
 }
 
 search_history () {
@@ -194,6 +189,7 @@ get_video_quality() {
 	# chooses the link for the set quality
 	dpage_url="$1"
 	video_links=$(decrypt_link "$dpage_url")
+    echo "$video_links" > a
 	case $quality in
 		best)
 			video_link=$(printf '%s' "$video_links" | head -n 4 | tail -n 1)
@@ -232,8 +228,8 @@ inf () {
 
 prompt () {
         # prompts the user with message in $1-2 ($1 in blue, $2 in magenta) and saves the input to the variables in $REPLY and $REPLY2
-        printf "\033[1;34m%s\033[1;35m%s\033[1;34m: \033[0m" "$1" "$2"
-        read -r REPLY REPLY2
+    printf "\033[1;34m%s\033[1;35m%s\033[1;34m: \033[0m" "$1" "$2"
+    read -r REPLY REPLY2
 }
 
 menu_line_even () {
@@ -268,6 +264,22 @@ menu_line_strong() {
 # INPUT PARSING #
 #################
 
+is_number () {
+	[ "$1" -eq "$1" ] 2>/dev/null || die 'Invalid number entered'
+}
+
+process_search () {
+	search_results=$(search_anime "$query")
+	while [ -z "$search_results" ]; do
+		err 'No search results found'
+		prompt 'Search Anime'
+		query="$REPLY $REPLY2"
+		search_results=$(search_anime "$query")
+	done
+	anime_selection "$search_results"
+	episode_selection
+}
+
 anime_selection () {
 	count=1
 	while read -r anime_id; do
@@ -286,7 +298,7 @@ anime_selection () {
 		choice="$REPLY $REPLY2"
 	fi
 	# Check if input is a number
-	[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
+    is_number "$choice"
 	# Select respective anime_id
 	count=1
 	while read -r anime_id; do
@@ -350,10 +362,10 @@ episode_selection () {
 
 check_input() {
 	# checks if input is number, creates $episodes from $ep_choice_start and $ep_choice_end
-	[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
+    is_number "$ep_choice_start"
 	episodes=$ep_choice_start
 	if [ -n "$ep_choice_end" ]; then
-		[ "$ep_choice_end" -eq "$ep_choice_end" ] 2>/dev/null || die "Invalid number entered"
+        is_number "$ep_choice_end"
 		# create list of episodes to download/watch
 		episodes=$(seq "$ep_choice_start" "$ep_choice_end")
 	fi
@@ -385,7 +397,7 @@ open_episode () {
 	# checking if episode is in range
 	while  [ "$episode" -gt "$last_ep_number" ] || [ -z "$episode"  ]
 	do
-		[ "$ep_choice_start" -eq "$ep_choice_start" ] 2>/dev/null || die "Invalid number entered"
+        is_number "$ep_choice_start"
 		if [ "$last_ep_number" -eq 0 ]; then
 			die "Episodes not released yet!"
 		else
@@ -465,7 +477,7 @@ open_episode () {
 ############
 
 # to clear the colors when exited using SIGINT
-trap 'printf "\033[0m"; exit 1' INT HUP
+trap 'printf "\033[0m";[ -n "$logfile".new ] && rm "$logfile".new;exit 1' INT HUP
 
 # default options
 player_fn="mpv" #video player needs to be able to play urls
@@ -552,29 +564,11 @@ case $scrape in
 			fi
 			query=$*
 		fi
-		search_results=$(search_anime "$query")
-		[ -z "$search_results" ] && die "No search results found"
-		anime_selection "$search_results"
-        	while [ "$REPLY" = "a" ]; do
-        		search_another_anime
-        	done
-        	[ "$REPLY" = "q" ] && exit 0
-        	if [ "$REPLY" -gt 0 ]; then
-			episode_selection
-        	else
-			die "invalid choice"
-        	fi
+        process_search
 		;;
 	history)
-		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
-		[ -z "$search_results" ] && die "History is empty"
-		search_results=$(search_for_unwatched "$search_results")
-		anime_selection "$search_results"
-		ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
-		while [ "$REPLY" = "a" ]; do
-        	search_another_anime
-        	done
-        	[ "$REPLY" = "q" ] && exit 0
+        search_history
+        [ "$REPLY" = "q" ] && exit 0
 		first_ep_number=0
 		result=$(get_dpage_link "$anime_id" "$first_ep_number")
 		[ -z "$result" ] && first_ep_number=1
@@ -583,9 +577,9 @@ case $scrape in
 		die "Unexpected Scrape type"
 esac
 
-	check_input
-	append_history
-	open_selection
+check_input
+append_history
+open_selection
 
 ########
 # LOOP #
@@ -622,7 +616,6 @@ if [ -z "$select_first" ]; then
 			ep_choice_start=$((episode - 1))
 			ep_choice_end=""
 			;;
-
 		s)	
 			episode_selection
 			;;
