fix: missing linebreak in quality-miss printf (#1043)

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-version_number="4.1.2"
+version_number="4.1.3"
 
 # UI
 
@@ -33,7 +33,7 @@ die() {
 
 help_info() {
 	printf "
-    Usage: 
+    Usage:
     %s [options] [query]
     %s [query] [options]
     %s [options] [query] [options]
@@ -152,7 +152,7 @@ select_quality() {
 	worst) result=$(printf "%s" "$links" | grep -E '^[0-9]{3,4}' | tail -n1) ;;
 	*) result=$(printf "%s" "$links" | grep -m 1 "$1") ;;
 	esac
-	[ -z "$result" ] && printf "Specified quality not found, defaulting to best" 1>&2 && result=$(printf "%s" "$links" | head -n1)
+	[ -z "$result" ] && printf "Specified quality not found, defaulting to best\n" 1>&2 && result=$(printf "%s" "$links" | head -n1)
 	printf "%s" "$result" | cut -d'>' -f2
 }
 
