attempt to fix a bug referenced in 'https://github.com/pystardust/ani-cli/pull/955#discussion_r1060512522'

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -83,8 +83,12 @@ update_script() {
 # checks if dependencies are present
 dep_ch() {
 	for dep; do
-		if ! command -v "$dep" >/dev/null; then
+        if ! command -v "$dep" >/dev/null; then
             die "Program \"$dep\" not found. Please install it."
+        elif [ "$dep" = "flatpak run io.mpv.Mpv" ]; then
+            if flatpak info io.mpv.Mpv 2>&1 | grep -q 'error'; then
+			    die "Program mpv not found. Please install it."
+            fi
         fi
 	done
 }
