Switched dir check to mkdir

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -138,11 +138,7 @@ dep_ch () {
 download () {
 	case $2 in
 		*m3u8*)
-			if [ ! -d "$download_dir" ] ; then
-				die "Directory \"$download_dir\" does not exist."
-			else 
-				ffmpeg -loglevel error -stats -referer "$1" -i "$2" -c copy "$download_dir/$3.mp4"
-			fi
+			ffmpeg -loglevel error -stats -referer "$1" -i "$2" -c copy "$download_dir/$3.mp4"
 			;;
 		*)	
 			axel -a -k -n 10 --header=Referer:"$1" "$2" -o "$download_dir/$3.mp4" ;;
@@ -531,7 +527,7 @@ while getopts 'svq:dp:chDUVa:xr:fn' OPT; do
 			player_fn='download'
 			download_dir="$OPTARG"
 			if [ ! -d "$download_dir" ] ; then
-				die "Directory \"$download_dir\" does not exist."
+				mkdir -p "$download_dir" || die "Couldn't create $download_dir"
 			fi
 			;;
 		n) scrape=New ;;
