Reorganised functions into labeled groups also made some minor adjusments to comments

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,6 +1,11 @@
 #!/bin/sh
 
-# dependencies: grep sed curl video_player
+# version umber
+VERSION="1.0.0"
+
+
+# dependencies: grep sed curl video_player 
+# optional dependency: aria2c (for)
 # video_player ( needs to be able to play urls )
 player_fn="mpv"
 
@@ -8,6 +13,7 @@ prog=$0
 logfile="${XDG_CACHE_HOME:-$HOME/.cache}/ani-hsts"
 base_url=$(curl -s -L -o /dev/null -w "%{url_effective}\n" https://gogoanime.cm)
 
+# printf color codes
 c_red="\033[1;31m"
 c_green="\033[1;32m"
 c_yellow="\033[1;33m"
@@ -17,6 +23,10 @@ c_cyan="\033[1;36m"
 c_reset="\033[0m"
 
 
+#######################
+# Auxiliary functions #
+#######################
+
 help_text () {
 	while IFS= read -r line; do
 		printf "%s\n" "$line"
@@ -25,7 +35,8 @@ help_text () {
 	Usage:
 	  $prog [-kv] [--dub] [-q <quality>] [-d | -p <download_dir>] [<query>]
 	  $prog [-kv] [--dub] [-q <quality>] -u | -n | -H
-	  $prog -h | -D
+	  $prog -h | -D | -U | -V
+
 	Options:
 	  -u shows anime from history with unwatched episodes
 	  -n show recent anime
@@ -39,12 +50,18 @@ help_text () {
 	  --dub play the dub version if present
 	  -v use VLC as the media player
 	  -U fetch update from github
+	  -V print version number and exit
+
 	Episode selection:
 	  Add 'h' on beginning for episodes like '6.5' -> 'h6'
 	  Multiple episodes can be chosen given a range
 	    Choose episode [1-13]: 1 6
 	    This would choose episodes 1 2 3 4 5 6
 	EOF
+}
+
+version_text () {
+    printf "$c_blue%s$c_reset%s\n" "Version: " "$VERSION"  >&2
 }
 
 
@@ -68,8 +85,24 @@ update_script () {
 	fi
 }
 
+dep_ch () {
+	for dep; do
+		if ! command -v "$dep" >/dev/null ; then
+			die "Program \"$dep\" not found. Please install it."
+		fi
+	done
+}
+
+# create history file
+[ -f "$logfile" ] || : > "$logfile"
+
+
+#############
+# Searching #
+#############
+
 search_new () {
-	# get anime name along with its id
+	# get recent anime name along with its id
 
 	curl -s "$base_url" |
 	sed -n -E '
@@ -81,7 +114,7 @@ search_new () {
 }
 
 search_anime () {
-	# get anime name along with its id
+	# get anime name along with its id for a search term
 	search=$(printf '%s' "$1" | tr ' ' '-' )
 
 	curl -s "$base_url//search.html" \
@@ -104,6 +137,29 @@ search_eps () {
 		}
 		'
 }
+
+search_for_unwatched () {
+	search_results=$*
+
+	unwatched_anime=""
+	while read -r anime_id; do
+		current_ep_number="$(search_eps "$anime_id")"
+		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
+		if [ "$current_ep_number" -ge "$history_ep_number" ]
+		then
+			unwatched_anime="$unwatched_anime$anime_id\n"
+		fi
+	done <<-EOF
+	$search_results
+	EOF
+	[ -z "$unwatched_anime" ] && die "No unwatched episodes"
+	printf "%s""$unwatched_anime"
+}
+
+
+##################
+# URL processing #
+##################
 
 get_dpage_link() {
 	# get the download page url
@@ -162,16 +218,13 @@ get_video_quality() {
 	printf '%s' "$video_link"
 }
 
-dep_ch () {
-	for dep; do
-		if ! command -v "$dep" >/dev/null ; then
-			die "Program \"$dep\" not found. Please install it."
-		fi
-	done
-}
 
-# get query
+#################
+# Input parsing #
+#################
+
 get_search_query () {
+	#allows the input of a querry in runtime (if none in argv)
 	if [ -z "$*" ]; then
 		printf "Search Anime: "
 		read -r query
@@ -179,13 +232,6 @@ get_search_query () {
 		query=$*
 	fi
 }
-
-# create history file
-[ -f "$logfile" ] || : > "$logfile"
-
-#####################
-## Anime selection ##
-#####################
 
 anime_selection () {
 	search_results=$*
@@ -233,28 +279,6 @@ anime_selection () {
 	EOF
 }
 
-search_for_unwatched () {
-	search_results=$*
-
-	unwatched_anime=""
-	while read -r anime_id; do
-		current_ep_number="$(search_eps "$anime_id")"
-		history_ep_number="$(sed -n -E "s/${anime_id}\t//p" "$logfile")"
-		if [ "$current_ep_number" -ge "$history_ep_number" ]
-		then
-			unwatched_anime="$unwatched_anime$anime_id\n"
-		fi
-	done <<-EOF
-	$search_results
-	EOF
-	[ -z "$unwatched_anime" ] && die "No unwatched episodes"
-	printf "%s""$unwatched_anime"
-}
-
-##################
-## Ep selection ##
-##################
-
 episode_selection () {
 	ep_choice_start="1"
 	if [ "$last_ep_number" -gt 1 ]
@@ -282,6 +306,11 @@ check_input() {
 		episodes=$(seq "$ep_choice_start" "$ep_choice_end")
 	fi
 }
+
+
+##################
+# Video Playback #
+##################
 
 append_history () {
 	grep -q -w "${selection_id}" "$logfile" ||
@@ -375,6 +404,7 @@ open_episode () {
 	fi
 }
 
+
 ############
 # Start Up #
 ############
@@ -392,7 +422,7 @@ navigation_type=0
 # navigation_type 0 - confirm selection by pressing enter
 # navigation_type 1 - no enter confirmation for selections
 
-while getopts 'hdDHknp:q:uvU-:' OPT; do
+while getopts 'hdDHknp:q:uvUV-:' OPT;
 	case $OPT in
 		h)
 			help_text
@@ -431,6 +461,10 @@ while getopts 'hdDHknp:q:uvU-:' OPT; do
 			update_script
 			exit 0
 			;;
+		V)
+			version_text
+			exit 0
+			;;
 		-)
 			case $OPTARG in
 				dub)
@@ -465,10 +499,10 @@ fi
 
 shift $((OPTIND - 1))
 
-########
-# main #
-########
 
+########
+# Loop #
+########
 
 case $scrape in
 	query)
