feat: added exit option in search menu (#462)
* fix: Adding exit option in search anime menu
organize code into function and adding exit and search another anime option into search anime menu.

fix: refactoring code
while loop is necessary for infinite search.

* chore: version bump 1.6.0 -> 1.6.1

* fix: regex pattern matching is not implemented
This is temporary solution

* version bump due to pr merge order

Co-authored-by: ura <ura@ura43.xyz>

diff --git a/ani-cli b/ani-cli
--- a/ani-cli
+++ b/ani-cli
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # version number
-VERSION="1.6.1"
+VERSION="1.6.2"
 
 
 # history file path
@@ -136,6 +136,24 @@ search_for_unwatched () {
 	printf "%s" "$unwatched_anime"
 }
 
+search_another_anime () {
+	tput reset
+	prompt "Search Anime"
+	query="$REPLY $REPLY2"
+	search_results=$(search_anime "$query")
+	[ -z "$search_results" ] && die "No search results found"
+	anime_selection "$search_results"
+	episode_selection
+}
+
+search_history () {
+	tput reset
+	search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
+	[ -z "$search_results" ] && die "History is empty"
+	search_results=$(search_for_unwatched "$search_results")
+	anime_selection "$search_results"
+	ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+}
 
 ##################
 # URL processing #
@@ -266,12 +284,14 @@ anime_selection () {
 		tput reset
 		choice=1
 	elif [ -z "$ep_choice_to_start" ] || { [ -n "$ep_choice_to_start" ] && [ -z "$select_first" ]; }; then
-		prompt "Enter number"
+        menu_line_alternate "search for another anime" "a"
+        menu_line_strong "exit" "q"
+		prompt "Enter choice"
 		choice="$REPLY $REPLY2"
 	fi
 
 		# Check if input is a number
-		[ "$choice" -eq "$choice" ] 2>/dev/null || die "Invalid number entered"
+		[ "$choice" -eq "$choice" ] 2>/dev/null || return 0
 
 		# Select respective anime_id
 		count=1
@@ -413,7 +433,7 @@ open_episode () {
 			die "Video URL not found"
 		fi
 
-		
+
 
 		case $player_fn in
 			vlc)
@@ -546,7 +566,13 @@ case $scrape in
 		search_results=$(search_anime "$query")
 		[ -z "$search_results" ] && die "No search results found"
 		anime_selection "$search_results"
-		episode_selection
+        while [ "$REPLY" = "a" ]; do
+            search_another_anime
+        done
+        [ "$REPLY" = "q" ] && exit 0
+        if [ "$REPLY" -gt 0 ]; then episode_selection
+        else die "invalid choice"
+        fi
 		;;
 	history)
 		search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
@@ -615,21 +641,10 @@ if [ -z "$select_first" ]; then
 			ep_choice_end=""
 			;;
 		a)
-			tput reset
-			prompt "Search Anime"
-			query="$REPLY $REPLY2"
-			search_results=$(search_anime "$query")
-			[ -z "$search_results" ] && die "No search results found"
-			anime_selection "$search_results"
-			episode_selection
+            search_another_anime
 			;;
 		h)
-			tput reset
-			search_results=$(sed -n -E 's/\t[0-9]*//p' "$logfile")
-			[ -z "$search_results" ] && die "History is empty"
-			search_results=$(search_for_unwatched "$search_results")
-			anime_selection "$search_results"
-			ep_choice_start=$(sed -n -E "s/${selection_id}\t//p" "$logfile")
+            search_history
 			;;
 
 		N)
@@ -647,7 +662,7 @@ if [ -z "$select_first" ]; then
 	check_input
 	append_history
 	open_selection
-	
+
 else
 	wait $!
 	exit
